### ISSUE TITLE
Remove Empty Last Line From package.xml

### ISSUE THREAD

**Issue by jonny-harte** [scolladon/sfdx-git-delta#265] opened 2022-03-16 12:13 UTC
The line-staged pre-commit hook in SFDX projects runs prettier on xml files which removes the empty last line on package.xml. This means a diff is always shown even when no actual updates are made to a package.xml.

Is it possible to remove this line of have the option to include / exclude it?

<img width="1510" alt="Screenshot 2022-03-16 at 12 12 16 pm" src="https://user-images.githubusercontent.com/6071669/158587307-f5658043-27f6-4974-a257-67c99fff602a.png">

**Comment by scolladon** [comment] 2022-03-16 15:02
Hi @jonny-harte !

Thanks for raising this issue !

I cannot reproduce on my side, each time I generate a delta package I do not have empty line at the end of the package.xml.
We made sure to mimic the behaviour of the metadata api for the package.xml generation:

- EOL should be `\n`
- tab indent should be done with 4 spaces
- no last EOL at the end of the file

Can you help us reproduce the behaviour ? Maybe I have misunderstood it.

**Comment by jonny-harte** [comment] 2022-03-16 15:25
Hi @scolladon thanks for getting back so quickly. Looks like an inconsistency with the metadata api and sfdx project tooling if `EOL should be \n`. I've added a step to prettier the package.xml straight after its created to resolve this.

**Comment by scolladon** [comment] 2022-03-16 15:53
Thanks @jonny-harte !

I change the label to question then and close this issue !

**Closed by scolladon** 2022-03-16 15:53 UTC
Labels: enhancement
