### ISSUE TITLE
When triggered using Jenkins pipeline sfdx-git-delta is not recognized but recognized using Git Bash / Visual Studio Code / CMD

### ISSUE THREAD

**Issue by shrishrimal-swapnil** [scolladon/sfdx-git-delta#317] opened 2022-07-08 14:12 UTC
Hello,

I am trying to integrate sfdx-git-delta plugins in my Jenkins CI / CD Pipeline. I have installed sfdx-git-delta plugin using below command.

sfdx plugins:install sfdx-git-delta

Post installation I have confirmed the same with sfdx plugins and I see the latest version has been installed.

![image](https://user-images.githubusercontent.com/95403058/178007470-cd01c0f2-fae7-4aa6-a992-89cbc8e4b90e.png)

I am able to get package/package.xml when I execute below command using either Visual Studio Code or Git Bash or CMD,

sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output .

However, when I use same commands in Jenkins pipeline, I get error message as mentioned below,

![image](https://user-images.githubusercontent.com/95403058/178008146-d483c35a-187d-43d9-ae54-1a58dfbf21ed.png)

To debug the issue, I tried to echo installed plugins using "sfdx plugins" in Jenkins pipeline script and I see below message stating that "no plugins are installed"

![image](https://user-images.githubusercontent.com/95403058/178008535-b88c633f-6b96-4fa1-8b6f-a3f98f564cf2.png)

I tried to navigate in Jenkins workspace using git bash and execute command to list sfdx plugins and I see the that latest plugin is installed.

Can anyone help me to understand what I am missing here ? As Jenkins is installed on the same machine on which SFDX CLI and sfdx-git-delta plugin is installed. Also, I have added path of SFDX CLI in Jenkins custom tool configuration.

Any help / suggestions are highly welcomed. 

Thanks!

**Comment by scolladon** [comment] 2022-07-09 09:53
Hi @shrishrimal-swapnil 

Thanks for raising this issue ! 

This issue looks like a duplicate of this [one](https://github.com/scolladon/sfdx-git-delta/issues/315) right ?

**Comment by shrishrimal-swapnil** [comment] 2022-07-11 04:09
Hi @scolladon

Thank you for your response.

I don't think this issue is duplicate of this [one](https://github.com/scolladon/sfdx-git-delta/issues/315).

The plugin is installed on the same machine where Jenkins is installed and there is no Docker in the picture. Through Jenkins, I am just triggering command which should get sfdx plugin, but that is not the case. Using simple Git Bash or Visual Studio Code terminal the sfdx plugin shows list of plugins installed whereas if executed through Jenkins pipeline, it says no plugins installed.

**Closed** 2022-07-11 12:43 UTC
Labels: dependencies
