### ISSUE TITLE
Unable to run  sfdx sgd:source:delta in docker

### ISSUE THREAD

**Issue by kravuri1987** [scolladon/sfdx-git-delta#207] opened 2021-11-16 05:42 UTC
Issue verification check :

- [x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
I am unable to run the sfdx sgd:source:delta in docker
```
docker run --rm sfdx-playground:c3303f7ce82434671ebfc0ce2f08752dbce4e611-51 sfdx sgd:source:delta --to HEAD --from 'HEAD^' --output /app/commited/ --generate-delta
{
  "error": ". is not a git repository",
  "output": "/app/commited/",
  "success": false,
  "warnings": []
}
```
---

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## Optional more information

---

**Comment by scolladon** [comment] 2021-11-16 08:12
Hi @kravuri1987 !

Thanks for raising this issue !

By the output of the plugin, it seems the directory used is not a git repository...
Maybe the scanned folder is not the right one ?
Maybe the docker instance used does not have git installed ?

**Comment by kravuri1987** [comment] 2021-11-16 12:37
Hi scolladon -thanks a lot for replying. I have a folder and git installed.Here is my docker file.

```
FROM alpine:latest

# Add packages
RUN apk --no-cache add \ 
    bash \
    openssh \
    git \
    openjdk8 \
    nodejs \
    npm \
    curl \ 
    wget \
    unzip \
    nss \
    && apk add apache-ant --no-cache --update-cache \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ \
    --allow-untrusted

# Download SFDX
RUN mkdir -p /sfdx \
    && curl -SL https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar -xJC /sfdx --strip-components 1 \
    && ln -sf /usr/bin/node /sfdx/bin/node \
    && /sfdx/install \
    && rm -rf /sfdx

RUN sfdx --version

# install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
RUN echo y | sfdx plugins:install sfdx-git-delta
RUN sfdx plugins

# legacy way to install SFDX-Git-Delta, if you still want to use the sgd command (not needed if you use the Salesforce CLI extension)
RUN npm install sfdx-git-delta@latest --global
RUN sgd --version

RUN apk add --no-cache git

WORKDIR /app
RUN mkdir -p /app/commited
RUN sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output /app/commited/ --generate-delta
```

**Comment by scolladon** [comment] 2021-11-16 13:12
Ok thanks,

Where is the actual folder containing the Salesforce sources ?
Where do you do a git clone of the Salesforce sources repository ?

**Comment by kravuri1987** [comment] 2021-11-16 13:17
I am checking out the git clone in Jenkins and invoking the docker build.
Jenkinsfile:
pipeline {
    agent any

    stages {
        stage('Check out code') {
            steps {
                deleteDir()
                sh """
                 git clone sfdx-playground -b ${env.CHANGE_BRANCH ?: BRANCH_NAME} .
                """
              }
              post {
                always {
                 updateGitlabCommitStatus name: "${STAGE_NAME}"
               }
            }
        }
        
        stage('Build Docker') {          
           steps {
             sh "docker build . -t sfdx-playground:${GIT_COMMIT}-${BUILD_NUMBER}"
           }
           post {
                always {
                 updateGitlabCommitStatus name: "${STAGE_NAME}"
               }
            }
        }
    }    
}

**Comment by scolladon** [comment] 2021-11-16 13:26
What does `git clone sfdx-playgournd -b ...` do ?

**Comment by kravuri1987** [comment] 2021-11-16 13:30
This clones the git repo and checks out the branch.

**Comment by scolladon** [comment] 2021-11-16 15:05
Then I do not know why it is not recognize as a git repository.

Are you able to reproduce it locally ?

**Comment by kravuri1987** [comment] 2021-11-16 15:19
I ran the dockerfile locally and got the same error.
=> ERROR [12/12] RUN sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output /app/commited/ --generate-delta                                                                                   2.1s
------                                                                                                                                                                                                 
 > [12/12] RUN sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output /app/commited/ --generate-delta:                                                                                              
#15 2.048 {                                                                                                                                                                                            
#15 2.048   "error": ". is not a git repository",
#15 2.048   "output": "/app/commited/",
#15 2.048   "success": false,
#15 2.048   "warnings": []
#15 2.048 }
------
executor failed running [/bin/sh -c sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output /app/commited/ --generate-delta]: exit code: 1

**Comment by scolladon** [comment] 2021-11-16 16:15
Are you running the plugin inside the folder of the cloned repository ?
I do not see a `cd` after the clone and the command does not use the `-r` parameter to tell where is the repo

**Comment by kravuri1987** [comment] 2021-11-16 18:19
Docker is running in a daemon thread. how do I pass the repo to the command?

**Comment by scolladon** [comment] 2021-11-16 22:10
You can do that by using the `--repo (-r)`[parameter](https://github.com/scolladon/sfdx-git-delta#sfdx-sgdsourcedelta--f-string--t-string--r-filepath--i-filepath--d-filepath--s-filepath--w--o-filepath--a-number--d---json---loglevel-tracedebuginfowarnerrorfataltracedebuginfowarnerrorfatal)
It takes a path to the folder containing the git repository where the Salesforce sources are

**Comment by kravuri1987** [comment] 2021-11-16 23:40
Thanks a lot scolladon.Really appreciate  and admire your passion

**Comment by scolladon** [comment] 2021-11-17 07:43
You're welcome !

Should I close this issue ?

**Comment by kravuri1987** [comment] 2021-11-17 22:08
Hi @scolladon Please close this issue.

**Closed** 2021-11-17 23:31 UTC
Labels: question

**Comment by luckyboyvijay** [comment] 2024-03-07 15:51
Hi @scolladon 

Can you please help me with this issue ? 

$ sf plugins:install sfdx-git-delta --verbose
(node:3646) Warning: Closing file descriptor 18 on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3646) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.
? This plugin isn't signed by Salesforce. Only install the plugin if you trust
its creator. Do you want to continue the installation?, (y/N)
$ echo "y"
y
$ sf --version
@salesforce/cli/2.30.8 linux-x64 node-v20.11.1
$ sf plugins
No plugins installed.
Uninstalled JIT Plugins:
community 3.0.21
custom-metadata 3.1.12
dev 2.1.13
devops-center 1.2.6
env 3.0.20
functions 1.22.11
signups 2.0.24
@salesforce/sfdx-plugin-lwc-test 1.1.1
@salesforce/sfdx-scanner 3.21.0

Running this on a gitlab ci on a ubuntu server hitting with above issue. looks like the plugin is not even installing here. But when i try it locally on my mac it works fine.

**Comment by scolladon** [comment] 2024-03-07 20:12
Hi @luckyboyvijay 

Did you have a look at those resources ?

- https://github.com/scolladon/sfdx-git-delta/discussions/325#discussioncomment-5552509
- https://github.com/scolladon/sfdx-git-delta/issues/512

Maybe it can help as it is related to docker issue/configuration that look like what you are describing
