### ISSUE TITLE
Allow metadata comparison from top level folder

### ISSUE THREAD

**Issue by busybox0** [scolladon/sfdx-git-delta#316] opened 2022-07-07 13:36 UTC
## Allow metadata comparison from top level folder.

If the project contains metadata folder as top level directory they are ignored by sgd
As a side note, such folder structure is useful while creating scratch orgs, when metadata can only be deployed in chunks, as there is built-in force:source:push logic for this.

### What is the parameter and the value you used with it?

Top level folders structure :
```
ls -la
drwxr-xr-x  9 ubuntu ubuntu 4096 Jul  1 18:31 ../
-rw-r--r--  1 ubuntu ubuntu 2313 Jun  2 12:20 .forceignore
drwxr-xr-x  9 ubuntu ubuntu 4096 Jul  7 16:18 .git/
-rw-r--r--  1 ubuntu ubuntu  883 Jul  6 15:16 .gitignore
drwxr-xr-x  3 ubuntu ubuntu 4096 Jun 17 10:32 force-app/
drwxr-xr-x  2 ubuntu ubuntu 4096 Jul  7 15:10 profiles/
-rw-r--r--  1 ubuntu ubuntu  427 Jul  7 15:55 sfdx-project.json

```
The folder **profiles** is reflected in sfdx-project.json:
```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    },
    {
      "path": "profiles",
      "default": false
    }
  ],
  "pushPackageDirectoriesSequentially": true,
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "54.0",
}
```
Let's imagine recent commits touched files stored in profiles folder, which is a peer folder along with with force-app.

```
git diff --name-status --no-renames HEAD~1 HEAD
M       profiles/Admin.profile-meta.xml
```
And now we executing sgd:
`sfdx sgd:source:delta --from HEAD~1 --to HEAD --output tmp --generate-delta`

### What is the expected result?

Profile files from folder **profiles** that were touched by recent commit(s) are being copied to --output tmp  and package.xml being generated accordingly.

### What is the actual result?
folder **profiles** completely ignored, even if explicitly stated in option `--source` :
```
$ sfdx sgd:source:delta --from HEAD~1 --to HEAD --output tmp --generate-delta  --source profiles
{
  "error": null,
  "output": "tmp",
  "success": true,
  "warnings": []
}
$ ls -l tmp/*
tmp/destructiveChanges:
total 8
-rw-r--r-- 1 ubuntu ubuntu 135 Jul  7 16:30 destructiveChanges.xml
-rw-r--r-- 1 ubuntu ubuntu 135 Jul  7 16:30 package.xml

tmp/package:
total 4
-rw-r--r-- 1 ubuntu ubuntu 135 Jul  7 16:30 package.xml
```
---

## Execution context

**Operating System:** WSL (Ubuntu 20.04)
**node version:** v14.17.6
**git version:**  2.25.1
**sfdx version:** sfdx-cli/7.157.0 wsl-x64 node-v14.17.6
**sgd plugin version:** 5.3.0

**Comment by scolladon** [comment] 2022-07-07 15:19
Hi @busybox0 

Thanks for raising this issue and thanks for your help improving the plugin.
The issue is very clear 👍

I have been able to reproduce the behaviour explained in this PR in our playground (branch [issue/316](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/316))

The profile metadata is contained under a top level folder and our algorithm checks for in between folder.
=> Top level folder cannot be metadata container folder, they should contain folder containing metadata (or other folder).

As a workaround I suggest you to put the profiles folder inside another top level folder.
In the reproduction playground I used a folder named `permissions` and made it works.
Let us know if it works for you and let's close this issue

@mehdisfdc It looks like a very minor bug to me because
- the workaround is very simple and straightforward
- the workaround is not a bad practice (the opposite)
- having metadata directly under a top-level folder is not very common and should be avoided IMHO

I prefer not to fix this.

#### Design information
The `sfdx-project.json` file is not parsed by the plugin.
It means it will also consider files located under folder not listed in the `sfdx-project.json`file !
We only use `ignore` files (`-i` and `-D` parameters) to drive what folder/files to bypass

We use folder name and file prefix to identify metadata kind (except for very particular cases).

**Comment by busybox0** [comment] 2022-07-08 11:40
Thanks Sebastien. Noted.

**Comment by scolladon** [comment] 2022-07-08 12:15
@busybox0 can we close this issue ?

**Comment by busybox0** [comment] 2022-07-09 07:52
Yes. It can be closed. Workaround is not painful at all. Thanks Sebastien.

But sfdx seems not obligatory require intermediate directories in project structure. My initial assumption was that if sfdx works this way, then the plugin would also follow this.

**Comment by scolladon** [comment] 2022-07-09 09:48
You're right, it should be able to work like sfdx does...
You are the first to raise this issue so far, we can keep this has an enhancement.

**Comment by scolladon** [comment] 2023-03-07 13:27
Closing this enhancement as there is not much traction and the effort is huge compared to the value behind (workaround is the best practice)

**Closed by scolladon** 2023-03-07 13:27 UTC
Labels: enhancement, good first issue
