### ISSUE TITLE
I can't find sgd-plugin when running on windows based gitlab-runner

### ISSUE THREAD

**Issue by hwanginaver** [scolladon/sfdx-git-delta#805] opened 2024-03-12 08:06 UTC
## What is the problem?

In Windows powdershell, sgd-plugins can be found normally.

I can't find sgd-plugin when running on windows based gitlab-runner

=> In window powershell
 yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
1.22.21
v21.6.2
git version 2.36.1.windows.1
@salesforce/cli/2.30.8 win32-x64 node-v20.11.1
@salesforce/sfdx-scanner 3.21.0
sfdx-git-delta 5.34.0

Uninstalled JIT Plugins:
community 3.0.21
custom-metadata 3.1.12
dev 2.1.13
devops-center 1.2.6
env 3.0.20
functions 1.22.11
signups 2.0.24

=> In gitlab-runner
sf sgd:source:delta -t HEAD -f HEAD~1 --output . -s force-app/main/default
 »   Warning: sgd source delta is not a sf command.

**Operating System:** …

**yarn version:** …
1.22.21
**node version:** …
v21.6.2
**git version:** …
git version 2.36.1.windows.1
**sfdx version:** …
@salesforce/cli/2.30.8 win32-x64 node-v20.11.1

**sgd plugin version:**
-

No plugins installed.
Uninstalled JIT Plugins:
community 3.0.21
custom-metadata 3.1.12
dev 2.1.13
devops-center 1.2.6
env 3.0.20
functions 1.22.11
signups 2.0.24
@salesforce/sfdx-plugin-lwc-test 1.1.1
@salesforce/sfdx-scanner 3.21.0

**Comment by scolladon** [comment] 2024-03-12 09:09
Hi @hwanginaver !

Thanks for raising this issue and thanks for contributing in making this project better!

Could you share the gitlab configuration please ? I'd like to be able to reproduce it and see for myself.

Is it link somehow to docker ? If so then maybe this [thread](https://github.com/scolladon/sfdx-git-delta/issues/512) can help

**Comment by hwanginaver** [comment] 2024-03-13 00:59
I did't use docker. I only copied the url below.
https://docs.gitlab.com/runner/install/windows.html

Is there a config file that sets the sfdx-cli to find a specific plugin?
Or do I need to add a specific path, or do I need file access permission?

**Comment by scolladon** [comment] 2024-03-13 09:16
> So when reinstalling sfdx-cli and reinstalling sgd plugin, I got the error below. Is that error not relevant?

Those are warnings, I think they are ok because we have not yet migrated to sf v2 plugin architecture as we still have a huge customer base on the old sfdx cli.

So, if I understand properly, this issue occurs when running "Gitlab runner" locally right ?
How the sfdx cli and the plugin are installed inside this runner ? Do you have a configuration file for that as well ?

**Comment by scolladon** [comment] 2024-03-25 09:15
Hi @hwanginaver 

Do you still have the issue ?
Did you have time to go through my questions to help me understand the issue and how to reproduce it ?

**Comment by scolladon** [comment] 2024-04-11 14:40
Closing the issue

If you still have the problem and have more information, feel free to reopen it.

**Closed by scolladon** 2024-04-11 14:40 UTC
Labels: bug
