### ISSUE TITLE
Delta is not generate for webStoreTemplate and globalValuesSet

### ISSUE THREAD

**Issue by LINDVIOR18** [scolladon/sfdx-git-delta#884] opened 2024-06-13 13:41 UTC
So everything works ok, but there are metadata escapes like for example, Global Values Set and Web Store Template, after generation, they don't appear in changeSet. Even if I do them separately or with all other metadata they never appear in the file as changes. 
sfdx-git-delta is used in the pipeline.

# Install Salesforce CLI plugin
RUN echo y | sfdx plugins:install sfdx-git-delta

**Comment by LINDVIOR18** [comment] 2024-06-14 08:44
<img width="273" alt="Screenshot 2024-06-13 at 17 18 03" src="https://github.com/scolladon/sfdx-git-delta/assets/49869785/3e4c0a3a-129c-46d4-bbb9-bc3774a81d46">
<img width="472" alt="Screenshot 2024-06-13 at 17 25 59" src="https://github.com/scolladon/sfdx-git-delta/assets/49869785/d547b565-d68a-4aa5-b040-74f25c4c46b7">
<img width="466" alt="Screenshot 2024-06-13 at 17 26 25" src="https://github.com/scolladon/sfdx-git-delta/assets/49869785/9f4a87ca-e1b0-4084-b246-d5b1dc6844a5">
<img width="871" alt="Screenshot 2024-06-13 at 17 37 45" src="https://github.com/scolladon/sfdx-git-delta/assets/49869785/5654460d-3b51-4813-afb2-00f9c7eda60b">

no yarn used

**Comment by scolladon** [comment] 2024-06-14 08:58
Thank you for that,

They should appear in the `destructiveChanges.xml` right ?
This is not the case currently ? When you say "ChangeSet" what do you mean ?

**Comment by LINDVIOR18** [comment] 2024-06-14 09:13
Sorry, I compared a blank branch on local and for that reason it appears as destructive, however I am now committing to a blank branch with no data as example UAT branch.
But in any case, none of them are found in destructiveChangeSet and chnageSet.
I previously tried deleting and adding them but they didn't appear and I was already doing it manually but now I decided to open the case.

**Comment by scolladon** [comment] 2024-06-14 09:41
Ok, I think I understand better.

Could you send me the exact steps to reproduce the issue please (with content)
And also what is the actual result compared to the expected result

Thanks in advance, it will greatly help me solving this problem precisely

**Comment by LINDVIOR18** [comment] 2024-06-14 10:06
[pipelineLog-{b05bd35e-77d3-4d77-a818-0e9176a128e1}.txt](https://github.com/user-attachments/files/15836548/pipelineLog-.b05bd35e-77d3-4d77-a818-0e9176a128e1.txt)

I'm sorry I can't provide more details such as file names but this is the metadata that is generated and it's ok except for those two that are missing.

**Comment by scolladon** [comment] 2024-06-14 14:45
I tried to reproduce the issue in our reproduction playground from what I understand here.
I may be different from your situation as I have not the exact steps to create the git content that generates the error.

Here is the branch : [`issue/884`](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/884)
I have created a webStoreTemplate (from the doc) and a globalValueSet (from the doc as well)
I have added them in git
And then I execute sgd (`sfdx sgd:source:delta -f HEAD~1 -d`)
I copies the global value set and the webStoreTemplate : 
```sh
output/sgd/reproduction/playground
├── globalValueSets
│   └── MyGVS.globalValueSet-meta.xml
└── webstoretemplate
    └── MyWebStoreTemplate.webstoretemplate-meta.xml
```

And it also generates this `package.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MyGVS</members>
        <name>GlobalValueSet</name>
    </types>
    <types>
        <members>MyWebStoreTemplate</members>
        <name>WebStoreTemplate</name>
    </types>
    <version>50.0</version>
</Package>
```

You can try on your own with the following commands:
```sh
$ git clone https://github.com/scolladon/sfdx-git-delta-reproduction-playground.git
$ cd sfdx-git-delta-reproduction-playground
$ git checkout issue/884
$ sfdx sgd:source:delta -f HEAD~1 -d
```

I think I am not able to reproduce
Maybe I need more information because I'm doing it wrong.
If so, please tell me exactly how to reproduce the issue

**Comment by LINDVIOR18** [comment] 2024-06-17 11:47
I generated it in the repository you sent and yes it's still ok and a year ago it was still ok when I used it for WebStore Template but now I don't understand what the problem is.
So I have tried to reproduce it in several ways but it doesn't work for me either I can't understand what the problem is. 
In your repository I can see that it works, in mine I tried to create 2 empty branches with no data to add WebStoreTemplate in the first one and compare but anyway it doesn't see them, but other metadata is ok.

**Comment by scolladon** [comment] 2024-06-17 12:29
Could you show the path of the webstore template file please ?

**Comment by scolladon** [comment] 2024-06-17 14:05
Ok I see why now...

Both the folder and the suffix of the file are incorrect.
This is why it failed both detection (suffix and folder) in the plugin

To fix that you should change the folder name from `webStoreSemplates` to `webstoretemplate` and the file suffix from `webStoreSemplate-meta.xml` to `webstoretemplate-meta.xml`
The plugin follows the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_webstoretemplate.htm) closely, sometimes more than `sfdx cli`.

Let me know if it fixed the issue and your side so we can close it :)

**Comment by LINDVIOR18** [comment] 2024-06-18 08:28
Yes that's fixed thank you,
But anyway I think it would be better if we use for the map webStoreTemplates and for the suffix webStoreTemplate which comes default when you do retrive with package.xml

At the moment when I do retries through the package it generates like this and it's a bit inconvenient to search why and change the name.

In any case thanks, so we can close the case and you can update the plugin if you want!?

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>WebStoreTemplate</name>
    </types>
    <version>60.0</version>
</Package>

**Comment by scolladon** [comment] 2024-06-18 09:14
Yes, I think too we should close it then.
I will not change the plugin because the plugin is compliant with what is said in the documentation.
I think the issue is in `sfdx cli` then, it should be fixed there so it retrieves the metadata in the right folder with the right format according to the doc

**Closed by scolladon** 2024-06-18 09:14 UTC
Labels: bug
