### ISSUE TITLE
Plugin is not getting installed using Docker file

### ISSUE THREAD

**Issue by rajendrasnagar** [scolladon/sfdx-git-delta#315] opened 2022-06-30 15:24 UTC
## What is the problem?

---
We are trying to create a Jenkins Image with SGD using Docker file. There is no error in the terminal, however the plugin is not getting installed.

### What is the parameter and the value you used with it?

Below is the Docker file used:
------------------------------------------------------------------------------------------------------------------
FROM jenkins/jenkins:2.263.3
USER root

RUN mkdir /.cache /.sf
RUN chown jenkins.jenkins /.cache -R
RUN chown jenkins.jenkins /.sf -R
RUN chmod 757 /.cache /.sf -R

#WORKDIR /

RUN apt-get update && apt-get install -y git ant xmlstarlet xz-utils

RUN apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh
  
RUN npm i sfdx-cli --global

RUN echo y | sfdx plugins:install sfdx-git-delta

USER jenkins

------------------------------------------------------------------------------------------------------------------

### What is the expected result?

Plugin should get installed. 

### What is the actual result?

Plugin is not installed, though there is no error on the terminal. 
![image](https://user-images.githubusercontent.com/3901703/176714840-7380cba4-ddd3-45dc-854c-f2028c04d645.png)

![image](https://user-images.githubusercontent.com/3901703/176714888-4a75e3f2-46e6-42e7-8adc-2e4abc0de690.png)

## Execution context

We are using this docker file on OpenShift platform.

Any help or feedback is appreciated as we are trying to resolve this from past week with no success.

**Comment by scolladon** [comment] 2022-06-30 15:47
Hi @rajendrasnagar !

Thanks for raising this issue.

Do you have the same issue whith other plugins ?

**Comment by rajendrasnagar** [comment] 2022-06-30 19:00
This is a section of output while building image. It says that plugin is installed, but lists none.
![image](https://user-images.githubusercontent.com/3901703/176757159-5b6447e1-1c07-4c05-ba19-cbdf8bad2e53.png)

**Comment by scolladon** [comment] 2022-06-30 19:02
Hum... then it does not seems to be an issue with our plugin...
You should investigate in the docket side, why the plugins are not available after installation there

**Comment by rajendrasnagar** [comment] 2022-07-01 06:33
Yes, it seems it is not sgd plugin issues. I think, I should raise it on other platform. 

However, before closing, if possible... do you have any working docker image for Jenkins with plugins installation. We have to check if it is OpenShift specific permission issue or not.

**Comment by scolladon** [comment] 2022-07-04 12:38
I think you can try this [one](https://github.com/mehdisfdc/sfdx-cli-gitlab/blob/master/Dockerfile). It is 4 month old, so it does not run the latest version but it may help identify your issue

**Comment by rajendrasnagar** [comment] 2022-07-08 15:17
Thanks @scolladon, it is working as expected. However, it is still not working with Jenkins plugins. I think we need to explore more.

**Comment by scolladon** [comment] 2022-07-08 18:25
Hi @rajendrasnagar, thanks for the update!

Before closing this issue, could you give more information about what is not working with Jenkins plug-in ?

**Comment by rajendrasnagar** [comment] 2022-07-10 17:46
@scolladon When I tried with the earlier one you mentioned (this [one](https://github.com/mehdisfdc/sfdx-cli-gitlab/blob/master/Dockerfile).), i.e. with nodejs base image. It is working as expected. 
However, with Jenkins image, we don't see plugins getting installed. Though in the terminal out, while building app from docker, it is mentioned that the plugins are installed. But indeed they are not.

**Comment by scolladon** [comment] 2022-07-10 18:04
Ok, thanks for the explanations.
I close this issue as it is not relevant to the plug-in itself and a workaround has been found.

If you find the root cause of this issue with Jenkins please explain it here, it will probably be useful to someone else

**Closed** 2022-07-10 18:04 UTC
Labels: dependencies

**Comment by gambe94** [comment] 2022-08-08 18:43
@rajendrasnagar 
In jenkins I managed it the following way:
I think these sfdx plugins deployed under the current user. In Jenkins has their own jenkins user.


```
RUN groupadd --gid 1000 jenkins \
   && useradd --uid 1000 --gid jenkins --shell /bin/bash --create-home jenkins
RUN echo 'jenkins ALL=(ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo

#Switch to jenkins user
USER jenkins
#sfdx plugin goigng to be installed .local directory under the current user
#sfdx plugin need to be installed under the running user!!
#Add sfpowerkit

RUN echo "y" | sfdx plugins:install sfpowerkit
#Add sfdx essentials
RUN echo 'y' | sfdx plugins:install sfdx-essentials
#ADD sfdx-git-delta
RUN echo "y" | sfdx plugins:install sfdx-git-delta

```

**Comment by scolladon** [comment] 2022-08-09 10:31
Hi @gambe94 

That is very nice finding, thanks for sharing !

I think it would be even more helpful in a [Discussion](https://github.com/scolladon/sfdx-git-delta/discussions/new?category=show-and-tell) !
Could you create it ? Or would you prefer me to do it ?

**Comment by scolladon** [comment] 2022-08-18 16:40
Hi @gambe94 

I just created the [discussion](https://github.com/scolladon/sfdx-git-delta/discussions/329).
Feel free to comment it!
