### ISSUE TITLE
Report Type change had not been pickup by sgd:source:delta action

### ISSUE THREAD

**Issue by kateluu-comdev** [scolladon/sfdx-git-delta#690] opened 2023-09-07 23:54 UTC
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

Hi team, 

Firstly thank for build, maintain and share the action 
Currently my development process is utilising sgd:source:delta (the action) to pickup the delta changes and deploy delta only
However, I just realise any change with ReportType had not been pickup by the action. 

In details, the when I add the new report type to repository and run the delta deployment action , the package.xml in this scenario return as below
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>56.0</version>
</Package>
There is no report type had been pickup .

In my test scenaraio,  I expect the delta process pickup my new report type and return the package.xml like below 
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
        <members>MyNewReportType</members>
        <name>ReportType</name>
    </types>
    <version>56.0</version>
</Package>

### What is the parameter and the value you used with it?

 here is my command
        - name: 'Compare and pickup delta change only'
        if: ${{steps.last_successful_commit.outputs.commit_hash != ''}}
        shell: bash
        run: sfdx sgd:source:delta --to "HEAD" --from ${{steps.last_successful_commit.outputs.commit_hash}} --ignore ignore --output .

### What is the expected result?

In my test scenaraio,  I expect the delta process pickup my new report type and return the package.xml like below 
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
        <members>MyNewReportType</members>
        <name>ReportType</name>
    </types>
    <version>56.0</version>
</Package>

### What is the actual result?

In my test scenaraio,  I expect the delta process pickup my new report type and return the package.xml like below 
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>56.0</version>
</Package>

## Steps to reproduce

1. Create salesforce dx project structure
2. Change/add new report type
3. Run delta action and check the package.xml file

## Execution context

---

**Operating System:** … ubuntu-latest

**yarn version:** …

**node version:** … v3

**git version:** … 

**sfdx version:** … https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz

**sgd plugin version:** …

**Comment by scolladon** [comment] 2023-09-08 09:00
Hi @kateluu-comdev !

Thanks for raising this issue and thanks for contributing in making this project better!

I'll try to reproduce it soon and let you know.
Could you give us more detail about the execution context ? (especially the plugin version)
```sh
$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
```

**Comment by scolladon** [comment] 2023-09-19 15:09
Hi @kateluu-comdev 

We close this issue because we do not have enough information to pursue.

Feel free to reopen it with the information asked so we can move forward on it.

**Closed by scolladon** 2023-09-19 15:09 UTC
Labels: bug
