### ISSUE TITLE
Error due to SFDX deprecation 

### ISSUE THREAD

**Issue by bmehtawebsummit** [scolladon/sfdx-git-delta#904] opened 2024-08-30 19:05 UTC
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
```
sfdx sgd:source:delta  --from $(git describe --match "${ORG_NAME}-*" --abbrev=0 --tags HEAD) --to HEAD --output . --ignore .forceignore --api-version "${API_VERSION}"

Error while using the above command : 
_(node:167) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:167) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(node:167) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
(node:167) Warning: Deprecated config name: apiVersion. Please use org-api-version instead._


```

## Steps to reproduce

---

## Execution context

---

**Operating System:** … Docker

**yarn version:** …

**node version:** …v20.17.0

**git version:** …git version 2.45.2

**sfdx version:** …sfdx-cli/47.15.1 linux-x64 node-v20.17.0

**sgd plugin version:** … should be the latest

## More information (optional)

---

**Comment by scolladon** [comment] 2024-08-31 09:51
Hi @bmehtawebsummit!

Thanks for raising this issue and thanks for contributing in making this project better!

I can see warnings but no errors.
And the only warning that I could address is the one referring to the api version parameter ((node:167) Warning: Deprecated config name: apiVersion. Please use org-api-version instead._).
This issue with the api version parameter is tracked in the issue #619 (maybe it is a duplicate)

Could you provide more information please ?
What is the actual error ? 
How can I reproduce ?

**Comment by bmehtawebsummit** [comment] 2024-09-02 14:06
HI @scolladon , 

Thanks for giving reference of the issue. So what I understood is the warning can be ignored ? for the warning below 
 
`_`((node:167) Warning: Deprecated config name: apiVersion. Please use org-api-version instead._).`_`

I am not using apiVersion config name in my entire script anywhere, I have double checked SGD command, putting below for your reference. 

`sfdx sgd:source:delta  --from $(git describe --match "${ORG_NAME}-*" --abbrev=0 --tags HEAD) --to HEAD --output . --ignore .forceignore --api-version "${API_VERSION}"`


If the warning can be ignored then I have a real issue that after sfdx sgd:source:delta command a package xml is generated but 

sfdx force:source:deploy -x ${PACKAGE_XML_PATH} -w 30 -u ${SF_USERNAME}

 command right after that is deploying more than specific in the package/package.xml. So I was wondering if this has something to do with the warning I am seeing.  This mainly happens when I am trying to create/update a field. It tried to deploy the entire object where previously it use to deploy just a field.

**Comment by scolladon** [comment] 2024-09-02 16:25
Hum... 

I think the plugin may have added the SObject in the package.xml, this is why then it could try to deploy the full object.
The plugin add the parent SObject when a master detail fields is added/modified and also add the master detail field when the parent SObject is modified. This is because of this [known issue](https://help.salesforce.com/s/articleView?id=000386883&type=1)

Could you show the diff (`git diff --name-status --no-renames <from> <to>`) and the content of the package.xml please ?

**Comment by bmehtawebsummit** [comment] 2024-09-05 19:12
HI @scolladon 

Sorry for the delay. 

For eg : I made a description adjustment on a field Cost__c on account object 

the output of 
git --no-pager diff --name-status HEAD prod-20240905110838 is 
M       force-app/main/default/objects/Account/fields/Cost__c.field-meta.xml

Package XML is 
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account.Cost__c</members>
        <name>CustomField</name>
    </types>
    <version>58.0</version>
</Package>


It is still attempting to deploy the entire object

**Comment by scolladon** [comment] 2024-09-05 20:15
That is weird...

Based on those new information I would say the plugin as done its job correctly.

The package.xml generated is expected.

What is concerning is the deploy command is deploying the whole object when asking to only deploy a field. 

What is the command used to deploy ?

**Comment by bmehtawebsummit** [comment] 2024-09-06 17:28
sfdx force:source:deploy -x package/package.xml  -w 30 -u ************************** -c  -l RunSpecifiedTests -r NoTestRun

**Comment by scolladon** [comment] 2024-09-07 10:39
> sfdx force:source:deploy -x package/package.xml -w 30 -u ************************** -c -l RunSpecifiedTests -r NoTestRun

I think this bug is located on the sfdx cli itself then...
I think the plugin has done its job and you would experience the same result if you build the `package.xml` by hand and try to deploy it.

If you agree I'll close this one
if you can drop the issue created on the cli I'll follow it

**Comment by bmehtawebsummit** [comment] 2024-09-11 16:37
Hi @scolladon  

I am raising ticket with salesforce cli but I wanted to confirm if my understanding is correct that SGD is still working on SFDX command?  sfdx commands have been deprecated and will be removed on Nov 2024 as per this link https://github.com/forcedotcom/cli/issues/2974

Please advise what is your plan on migration and what would you advise to me that should I check for SFDX or try changing to sf command ?

**Comment by scolladon** [comment] 2024-09-11 16:57
Hi @bmehtawebsummit,

We are migrating soon to the new plugin v2 architecture.
The actual command line is both compatible with sfdx cli and sf cli.
After migrating it will still be the case as well.

I think you should migrate to sf command 👍

**Closed by scolladon** 2024-09-11 16:57 UTC
Labels: bug

**Comment by bmehtawebsummit** [comment] 2024-09-11 22:56
I tried  
sf sgd source delta --from $(git describe --match "${ORG_NAME}-*" --abbrev=0 --tags HEAD) --to HEAD --output . --ignore .forceignore --api-version "${API_VERSION}"

and getting following error 

›   Warning: sgd source delta is not a sf command.
 Did you mean force source delete? (Y/n)
 ›   Error: Run sf help for a list of available commands.

**Comment by scolladon** [comment] 2024-09-12 06:06
Have you tried `sf sgd:source:delta ...` ?

**Comment by bmehtawebsummit** [comment] 2024-09-12 09:10
yes, I tried that too.

**Comment by scolladon** [comment] 2024-09-12 09:27
What you can do is:
- install `sf` cli
- use the `sfdx` compatibility command shipped with `sf` cli installation

We are currently working on migrating to the plugin v2 architecture.
It will work with `sf` command soon

**Comment by bmehtawebsummit** [comment] 2024-09-12 09:38
Hi, 

I have written following in my docker file  : 


RUN npm install @salesforce/cli --global
RUN sf --version
RUN sf plugins install sfdx-git-delta
RUN sf plugins

Please let me know what should I change here?

**Comment by bmehtawebsummit** [comment] 2024-09-12 21:08
thanks for your help
