### ISSUE TITLE
The plugin is not creating force-app with option --generate-delta

### ISSUE THREAD

**Issue by rgomezflores** [scolladon/sfdx-git-delta#441] opened 2023-02-02 01:19 UTC
## What is the problem?

I installed the plugin and I used the command: 

```
> mkdir changed-sources
> sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta
```

As you mentioned in the readme, just to try to get the same (obviously into my own repo), but the force-app is not created!

```
> 582520@DDC-VD-0078 MINGW64 ~/OneDrive - TMNA/Documents/repos1/cmud-bec-app (test04_SGD)
> $ mkdir changed-sources
> sfdx sgd:source:delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta
> {
>   "error": null,
>   "output": "changed-sources/",
>   "success": true,
>   "warnings": []
> }
```

The output is into new directory (changed-sources), I could see 2 directories: package & destructiveChanges, but not force-app!

Is it something missed?

**Comment by scolladon** [comment] 2023-02-02 09:48
Hi @rgomezflores !

Thanks for raising this issue and thanks for contributing in making this project better!

Let's check a few things:
- What is the sgd version you are using (`latest-rc` is `v5.11.4`) ? (`sfdx plugins`) 
- What is the context of execution ? (os version, node version, git version, sfdx cli version `uname -v ; node -v ; git --version ; sfdx --version ; sfdx plugins`)
- What is the content of the package.xml (`cat changed-sources/package/package.xml`) ?
- What is the content of the destructiveChanges.xml (`cat changed-sources/destructiveChanges/destructiveChanges.xml`) ?
- What is the output of this command `git diff --name-status --no-renames HEAD~1 HEAD` ?

How can I reproduce it on my local machine ?
Could you create a fork on our [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) with the minimal content/commit to reproduce ?

**Comment by rgomezflores** [comment] 2023-02-02 15:15
Hi @scolladon thanks for your quick response!

Related the questions that you are asking me, I could confirm the plugin version that I am using is the **v5.11.1**, not the last one, but I just installed the package using the procedure that is showed in the README.

This plugin is used into windows OS v10.x, nodejs version is up v14, for git is v2.26 for win, sfdx v7.120 and it is the unique plugin.

The resto of the questions is difficult to response to you, because is a customer Project and there are restrictions to expose the info. but as I commented you this:
```
> What is the content of the package.xml (cat changed-sources/package/package.xml) ?
> What is the content of the destructiveChanges.xml (cat changed-sources/destructiveChanges/destructiveChanges.xml) ?
```
is created with the minimum values...

sorry if I cannot share more details... if it is useful, I will try to make a test in my local.

**Comment by scolladon** [comment] 2023-02-02 15:24
Hi @rgomezflores !
Thanks for those details answers.
I understand for the information related to your customer, you're right to protect his privacy and we encourage it as well. Thanks for that.
I wanted to know if those files are populated correctly. It seems to be the case!

Could you try with the `latest-rc` version please ? It embed a couple of fixes related to windows.
```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
```

If you still have the issue with the `latest-rc` version ,then I encourage you to:

1. [fork our playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground)
2. create a branch with the minimal obfuscated data possible to reproduce it on your machine
3. communicate with us the branch on your fork and what command I should run to reproduce it with your settings (node version, git version and os version)

**Comment by rgomezflores** [comment] 2023-02-02 15:57
Sure @scolladon thanks to understand!

Let me try to reinstall the latest plugin, and I will let you know if that solved my issue... or a new update!

Thanks, and I will keep you informed.

**Comment by rgomezflores** [comment] 2023-02-02 16:46
It seems the issue wat the previous version!
I did a quick test, but let me try with another repo... again, I'm going to keep you posted!
THANKS!

**Comment by scolladon** [comment] 2023-02-03 08:56
Let's close this issue then

@rgomezflores feel free to reopen it if you find something else related to that

**Closed by scolladon** 2023-02-03 08:56 UTC
Labels: bug, reproduction steps needed
