### ISSUE TITLE
Generate delta command not working after migrating from sfdx to sf

### ISSUE THREAD

**Issue by Tanvidh** [scolladon/sfdx-git-delta#746] opened 2024-01-03 04:48 UTC
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
SGD command fro generating git delta is failing after migrating sfdx to sf
Version:
Sf:2.11.8
SGD:5.10.0

---

Getting error for this command
As
error running SGD:source:delta : core_1.Flags.enum is not a function

### What is the expected result?
Git delta should get generated

### What is the actual result?

error

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by Tanvidh** [comment] 2024-01-03 04:49
Command used:
Sfdx sgd:source:delta --to branchname --from $(git merge-base branchname) --repo . -outpu delta-source/ --generate-delta

**Comment by scolladon** [comment] 2024-01-03 04:55
Hi @Tanvidh!

Thanks for raising this issue and thanks for contributing in making this project better!

Could you try with the latest version of sgd please ?
Also can you try with the `--output` parameter (instead of `--outpu`) please ?

Let us know what it changes

**Comment by Tanvidh** [comment] 2024-01-03 05:20
Hi @scolladon ,
I tried using latest version for SGD 5.31.1
And command is also using --output.But still it is failing with same error
Nodejs version:18.18.2
Npm version:10.0.0

**Comment by scolladon** [comment] 2024-01-03 06:01
Thanks @Tanvidh, could you try uninstalling the plugin, uninstalling sf cli, and then reinstalling everything back please ?

**Comment by Tanvidh** [comment] 2024-01-03 06:19
Hi @scolladon ,
We are using CI-CD pipeline which freshly installs the Salesforce cli with every run.
Do you still want to try?.
If yes,if it will work after uninstalling and reinstalling what if we move it main prod level.It would be affect all the pipelines?

Please suggest

**Comment by scolladon** [comment] 2024-01-03 07:15
Thanks for the context of execution.
Could you give us more details about it ? What kind of CI/CD ? What OS ?

On our github action pipeline checks everything looks fine for any OS (mac, minux, windows) for node 18 and node 20.

**Comment by Tanvidh** [comment] 2024-01-03 07:47
Hi @scolladon ,
It is Jenkins CI-CD pipeline.Where in we have Jenkins stage fro generating delta stage
OS is linux-x64
Node 18

**Comment by scolladon** [comment] 2024-01-03 09:13
Could you share the pipeline definition @Tanvidh ?

Here is a [discussion](https://github.com/scolladon/sfdx-git-delta/discussions/325) about `sgd` installation on Jenkins. I don't know if it can help but we never know

**Comment by Tanvidh** [comment] 2024-01-05 12:12
Hi @scolladon ,
Thanks but I am using same commands and everything looks fine from my side.Il share the pipeline file with you .
Meanwhile I just wanted to understand regarding Jenkins node to be used to run node js 20 version and npm 18 version.
Is their any dependency whether we need to use Rhel8 for running the node js > 16 and npm > 14.
Iam using Rhel 8 node agent for running my code on Jenkins.Initially I tried using Linux-Aws but it was failing while installing node js version itself.

**Comment by scolladon** [comment] 2024-01-05 16:01
Hi @Tanvidh,

I actually do not know what kind of Jenkins setup you need to have to use the plugin.
I have never done that.

I found this [documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ci_jenkins.htm) about how to setup Jenkins to support sfdx.
I don't know if it works with sf.

We make sure the plugin supports the same node version as the sf cli does to ensure maximum compatibility

**Comment by Tanvidh** [comment] 2024-01-17 05:23
Hi @scolladon -Jenkins setup is sorted as sfdx commands are working fine on Jenkins.After migration from sfdx to sf it was working fine.But as the node js version got updated we started facing issues.
For now plugins have been installed correctly.its just failing in generate delta command

**Comment by scolladon** [comment] 2024-01-17 09:04
Hi @Tanvidh,

Why it is failing in generate delta command ?
What is the output you have actually, and what is the output you expect ?

**Comment by Tanvidh** [comment] 2024-01-18 05:18
It is failing with error as mentioned above 
Parameters used are source branch,target branch ,and output file.Command is also pasted above
Expected output is package.xml gets created at specified location
It's simple sfdx git delta plugin wherein generate delta command is used.

**Comment by scolladon** [comment] 2024-01-18 09:18
Ok @Tanvidh, thanks
Just to be sure, you are not experiencing the same issue locally, right ?
If so, I would try reinstalling everything.
Make sure it has `node` 18 or 20, `git` latest and `yarn`.

**Comment by Tanvidh** [comment] 2024-01-18 09:26
I will try to install locally.But local system is windows and Jenkins is using Linux.So iam trying directly onto Jenkins.
Git version is 2.39.2
Yarn:1.22.21
Nodejs:tried both 18 and 20

**Comment by Tanvidh** [comment] 2024-01-22 12:18
Hi @scolladon 
Any update on this?

**Comment by scolladon** [comment] 2024-01-22 13:54
Not on my side.

I am not able to reproduce the issue.
And others have been able to install sfdx cli and sgd on jenkins.

There may be something special with your installation / environment / jenkins setup
I am afraid without poking around I won't be able to help as I don't see much "unusual" things here

**Comment by scolladon** [comment] 2024-01-29 09:54
Hi @Tanvidh 

Do you have an update on your situation here ?

**Comment by scolladon** [comment] 2024-02-16 14:08
Yes sure, we can connect, my email is public on my profile, we could arrange a screen share next week

**Comment by scolladon** [comment] 2024-03-25 09:14
Hi @Tanvidh !

Do you still have the issue ?
How can I help here ?

**Comment by Tanvidh** [comment] 2024-03-26 05:20
Hi @scolladon -Thanks it's resolved for me .I had to add an extra package @salesforce/source-deply-retrieve in package.json and the issue got resolved.

**Comment by scolladon** [comment] 2024-03-26 08:32
That's great news @Tanvidh !

Where did you have to add this extra package ?
Maybe your issue is linked to [this one](https://github.com/scolladon/sfdx-git-delta/issues/804) and is fixed without having you to add this extra package

**Closed by scolladon** 2024-03-26 08:32 UTC
Labels: bug, reproduction steps needed, CI/CD
