### ISSUE TITLE
Some Specific Wave metadata type Components are not added in Output directory

### ISSUE THREAD

**Issue by anish1310** [scolladon/sfdx-git-delta#286] opened 2022-04-08 08:23 UTC
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---
We are getting a problem with generating delta with source code in a separate folder for wave component (Tableau Components)

There are some wave component differences between the branches, and the package.xml for wave components generated after running the source:delta command is correct but  it didn't add the following wave  metadata type components in the output directory:

1. WaveApplication
2. WaveDataset
3. WaveXmd

### What is the parameter and the value you used with it?
sfdx sgd:source:delta --to "source-branch" --from "target-branch" --output output-dir/ -d

### What is the expected result?
WaveApplication, WaveDataset, WaveXmd type components should be added in the output directory, even though they are generated in the package.xml which got generated

### What is the actual result?
No WaveApplication, WaveDataset, WaveXmd added in the output directory
Sample package.xml
```
<types>
        <members>Changed_Wave_App</members>
        <name>WaveApplication</name>
</types>
<types>
        <members>Changed_Wave_Dataset</members>
        <name>WaveDataset</name>
   </types>
<types>
        <members>Changed_Wave_Xmd</members>
        <name>WaveXmd</name>
 </types>
```

## Steps to reproduce
1. Modify or add some WaveApplication, WaveDataset, WaveXmd
2. commit into a branch
3. Execute command: sfdx sgd:source:delta --to "source-branch" --from "target-branch" --output output-dir/ -d
4. Check for the mentioned wave components in the output-dir/

---

## Execution context

Operating System: MacOS Big Sur 11.6
yarn version: …

node version: …

git version: 2.30.1 (Apple Git-130)

sfdx version: sfdx-cli/7.144.2 darwin-x64 node-v16.14.2

sgd plugin version: sfdx-git-delta 5.1.2

---

## More information (optional)

---

**Comment by scolladon** [comment] 2022-04-08 08:25
Hi @anish1310 

Thanks for raising this issue.
Sorry for the inconvenience.

I'll have a look in the coming days to qualify this issue.

Stay tuned!

**Comment by scolladon** [comment] 2022-04-08 15:07
Hi @anish1310 

I have investigated a little bit.
I was not able to reproduce... On my side it is working fine:
* the package.xml contains the wave component ✅
* the output folder contains the wave component files ✅

I created a branch [issue/286](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/286) on the reproduction playground to do so.
You can checkout this branch and try locally to run sgd:
```bash
$ git clone https://github.com/scolladon/sfdx-git-delta-reproduction-playground.git
$ cd sfdx-git-delta-reproduction-playground
$ git checkout issue/286
$ sfdx sgd:source:delta -d -f "HEAD~1"
$ cat output/package/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>WaveApplicationTest</members>
        <name>WaveApplication</name>
    </types>
    <types>
        <members>WaveDataSetTest</members>
        <name>WaveDataset</name>
    </types>
    <types>
        <members>WaveXmlTest</members>
        <name>WaveXmd</name>
    </types>
    <version>54.0</version>
</Package>
$ tree output/sgd
output/sgd
└── reproduction
    └── playground
        └── wave
            ├── WaveApplicationTest.wapp
            ├── WaveDataSetTest.wds
            └── WaveXmlTest.xmd
```

Could you try on your side and see if you still have the issue ?
Also I'm wondering how is your file structure, and specifically in which folder the wave files are located on your side ?
Could you give us an extract scoped for wave components (`$ tree your-force-app-folder/`) ?

### My environment
* Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
* yarn 1.22.15
* node v14.19.0
* git 2.35.1
* sfdx-cli/7.143.0 darwin-x64 node-v14.19.0
* sfdx-git-delta 5.1.2

**Comment by vaibhavdangar-woolies** [comment] 2022-04-21 09:58
Hi @scolladon , trust you doing good! 
We are facing a similar issue with 'wave' metadata type, where the sgd plugin seems unable to add  support file in directory, later causing to fail the validation step with Salesforce sandbox 

Details below:
---------------------------------------------------------
**Source file** (as seen in Github PR - Files changed): force-app/main/default/wave/ABC_Landing_Dashboard.wdash

**Get delta command:** 
export SOURCE_API_VERSION=$(cat sfdx-project.json  | jq -r .sourceApiVersion)
echo "In sfdx-project.json sourceApiVersion=$SOURCE_API_VERSION"
export LAST_DEPLOYED_COMMIT=$(git show-ref -s refs/remotes/origin/POC)

sfdx sgd:source:delta -t HEAD -f $LAST_DEPLOYED_COMMIT --output "/__w/1/s/artifact_1234" --generate-delta --api-version=$SOURCE_API_VERSION

**Output:** 
/__w/1/s/store-wpay-merchant-portal
In sfdx-project.json sourceApiVersion=54.0
{
  "error": null,
  "output": "/__w/1/s/artifact_1234",
  "success": true,
  "warnings": []
}

**Package.xml in artifacts**
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>ABC_Landing_Dashboard</members>
        <name>WaveDashboard</name>
    </types>
    <version>54.0</version>
</Package>

 **cat .\destructiveChangesPost.xml**
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>54.0</version>
</Package>

**Physical files in output:** Delta package generated by the sgd plugin and has only one file.

└───artifact_1234
    │   .forceignore
    │   sfdx-project.json
    │
    ├───destructiveChanges
    │       destructiveChanges.xml
    │       package.xml
    │
    ├───force-app
    │   └───main
    │       └───default
    │           └───wave
    │                   ABC_Landing_Dashboard.wdash
    │
    └───package
              destructiveChangesPost.xml
              Package.xml
	

**Validation error :** 
Command: 
sfdx force:source:deploy -l NoTestRun --checkonly -x /__w/1/s/artifact_1234/package/package.xml --postdestructivechanges /__w/1/s/artifact_1234/package/destructiveChangesPost.xml -u USERNAME@ABC.com --verbose  --wait 360

**Output:** ERROR running force:source:deploy:  No source-backed components present in the package.

**With another third party tool:** same object generate 2 files as output and validates successfully with Salesforce sandbox.

ABC_Landing_Dashboard.wdash
**ABC_Landing_Dashboard.wdash-meta.xml (<---file absent via sgd plugin)**

**cat ABC_Landing_Dashboard.wdash-meta.xml**
<?xml version="1.0" encoding="UTF-8"?>
<WaveDashboard xmlns="http://soap.sforce.com/2006/04/metadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <content xsi:nil="true"/>
    <application>ABC_App</application>
    <description>ABC_Landing_Dashboard - final</description>
    <masterLabel>ABC Landing Dashboard</masterLabel>
</WaveDashboard>


----------------------------------------------------------
**Environment:**
 Azure DevOps pipelines, using container: salesforce/salesforcedx:latest-full
Ubuntu 20.04.4 LTS
Version: 20220410.2

git version 2.35.1
git-lfs/3.1.2 (GitHub; linux amd64; go 1.17.6)

sfdx-cli/7.146.1 linux-x64 node-v16.13.2
@salesforce/cli/1.24.0 linux-x64 node-v16.13.2

@salesforce/sfdx-scanner 2.13.1
sfdx-git-delta 5.1.2
----------------------------------------------------------

**Comment by scolladon** [comment] 2022-04-21 10:10
Hi @vaibhavdangar-woolies !

Thanks for those information.
I was not aware of the dashboard metadata having meta file.

I will trouble shoot it in the coming days and try to propose a fix.

What is the other third party tool you mentioned  ?

**Comment by vaibhavdangar-woolies** [comment] 2022-04-21 10:50
Hi @scolladon , 
Appreciate your quick response.

-Files with extensions in wave directory
.wdash, .wdash-meta.xml
.wds-meta.xml,
.xmd-meta.xml,
.wdf, .wdf-meta.xml
.wpr, .wdpr-meta.xml
.wlens, .wlens-meta.xml

- third party tool - Gearset

I hope you are able to resolve this issue quickly, as we are blocked at the moment.
Thank you !

**Comment by scolladon** [comment] 2022-04-21 10:51
I wonder why you are facing this issue as the deployment is done based on the package.xml content and not from the generated source. Normally, using `sfdx force:source:deploy -x`, it should deploy from your code base and not from the delta source generated, unless the delta generated folder (`/__w/1/s/artifact_1234/`) is listed in your `sfdx-project.json` right ?

**Comment by vaibhavdangar-woolies** [comment] 2022-04-21 11:14
In the Azure DevOps pipeline steps:

1. we copy certain files:
```
cp ./sfdx-project.json ./artifact_1234
cp ./.forceignore ./artifact_1234
cp /__w/1/s/artifact_1234/destructiveChanges/destructiveChanges.xml /__w/1/s/artifact_1234/package/destructiveChangesPost.xml
```
2. In validation step, 
`cd /__w/1/s/artifact_1234` to the delta generated folder and then run the `sfdx force:source:deploy -x` 

3. In sfdx-project.json from source
```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "name": "AppName",
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "54.0"
}

```

**Comment by scolladon** [comment] 2022-04-21 11:30
@vaibhavdangar-woolies Thanks for your answers !

We have created a [fix for this issue](https://github.com/scolladon/sfdx-git-delta/pull/293), the PR is currently under review.
Could you test it on your side and let us know if it does the job from your point of view please ?
You can follow [those steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to do so

**Closed** 2022-04-21 13:42 UTC
Labels: bug, good first issue, reproduction steps needed

**Comment by scolladon** [comment] 2022-04-21 13:46
New version released (5.2.0) with the fix @vaibhavdangar-woolies & @anish1310 
You can give feedback here

**Comment by vaibhavdangar-woolies** [comment] 2022-04-21 14:02
Hi @scolladon , Issue resolved, able to see the meta files in the delta output directory.
Thanks a ton !

**Comment by scolladon** [comment] 2022-04-21 14:06
Happy incremental deployment guys !
