### ISSUE TITLE
CIRCLE CI Installation issue

### ISSUE THREAD

**Issue by IDERASFDC** [scolladon/sfdx-git-delta#160] opened 2021-07-02 21:05 UTC
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

---This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Finished digital signature check.
Installing plugin sfdx-git-delta... yarn add v1.22.10
Installing plugin sfdx-git-delta... info No lockfile found.Installing plugin sfdx-git-delta... [1/4] Resolving packages...Installing plugin sfdx-git-delta... [2/4] Fetching packages...Installing plugin sfdx-git-delta... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfdx-git-delta... failed
warning sfdx-git-delta > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfdx-git-delta > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning sfdx-git-delta > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
error sfdx-git-delta@4.6.1: The engine "node" is incompatible with this module. Expected version ">=14.6.0". Got "12.18.3"
error Found incompatible module.
    Error: yarn add --force sfdx-git-delta@latest --non-interactive 
    --mutex=file:/home/circleci/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/home/circleci/.cache/sfdx/yarn --check-files 
    exited with code 1

Installing Dependencies... 
--2021-07-02 21:02:22--  https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
Resolving developer.salesforce.com (developer.salesforce.com)... 199.232.65.145
Connecting to developer.salesforce.com (developer.salesforce.com)|199.232.65.145|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22101004 (21M) [application/x-tar]
Saving to: ‘sfdx-linux-amd64.tar.xz’

sfdx-linux-amd64.ta 100%[===================>]  21.08M  --.-KB/s    in 0.1s    

2021-07-02 21:02:22 (215 MB/s) - ‘sfdx-linux-amd64.tar.xz’ saved [22101004/22101004]

One or more target directories or files are not writeable; sudo permissions required.
sfdx installed to /usr/local/bin/sfdx
sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3
Installing SFDX Git Delta... 
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Finished digital signature check.
Installing plugin sfdx-git-delta... yarn add v1.22.10
Installing plugin sfdx-git-delta... info No lockfile found.Installing plugin sfdx-git-delta... [1/4] Resolving packages...Installing plugin sfdx-git-delta... [2/4] Fetching packages...Installing plugin sfdx-git-delta... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfdx-git-delta... failed
warning sfdx-git-delta > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfdx-git-delta > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning sfdx-git-delta > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
error sfdx-git-delta@4.6.1: The engine "node" is incompatible with this module. Expected version ">=14.6.0". Got "12.18.3"
error Found incompatible module.
    Error: yarn add --force sfdx-git-delta@latest --non-interactive 
    --mutex=file:/home/circleci/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/home/circleci/.cache/sfdx/yarn --check-files 
    exited with code 1

Exited with code exit status 1
CircleCI received exit code 1
### What is parameter and their value you used

wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
 tar xJ -C sfdx -f ./sfdx-linux-amd64.tar.xz --strip-components 1
 ./sfdx/install || { echo "error during sfdx installation"; exit 1; }
-echo "Node version : " && node --version || { echo "node not found"; exit 1; }
-echo "Npm version : " && npm --version || { echo "npm not found"; exit 1; }
 echo "Installing SFDX Git Delta... "
 echo y | sfdx plugins:install -f sfdx-git-delta
 sfdx plugins
### What is the expected result

success

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

## Optional more information

---

**Comment by scolladon** [comment] 2021-07-02 22:49
Hi @IDERASFDC !

Thanks for your interest in the plugin.
It seems the circle ci does not have the right configuration to install the plugin : 
> error sfdx-git-delta@4.6.1: The engine "node" is incompatible with this module. Expected version ">=14.6.0". Got "12.18.3"
error Found incompatible module.

Have you tried to set node to the latest v14 for this circle ci job ?

**Comment by IDERASFDC** [comment] 2021-07-07 18:36
yes, i set the node latest version.

**Comment by scolladon** [comment] 2021-07-08 08:27
Hi @IDERASFDC !

Ok then I need to have a way to reproduce it myself and poke around.
Could you send the minimal CircleCI configuration to reproduce this issue please ?

**Comment by scolladon** [comment] 2021-11-17 13:53
Do you still need our help on this issue ?
If not then we will close this issue.

**Comment by scolladon** [comment] 2021-12-17 21:51
Closing this Issue because it is open for too long without activity.

Feel free to reopen it if needed, with new information to help investigate further

**Closed by scolladon** 2021-12-17 21:51 UTC
Labels: question
