### ISSUE TITLE
[BUG NAME] plugin not identifying added files, only modified

### ISSUE THREAD

**Issue by fedegiust** [scolladon/sfdx-git-delta#190] opened 2021-09-16 19:25 UTC
Issue verification check :

- [ ] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?
Not deployable, build fails because it's not identifying added files.
## What is the problem

---

### What is the expected result

The expected result is to include the added files

### What is the actual result

Only adds the modified files to the package.xml

## Steps to reproduce

---

- Create a branch
- Modify a file and add a new one
- Add the new file to the commit and commit the changes
- Modify another file and create a new commit
- On the new branch, execute this
- sfdx sgd:source:delta --to "origin/master" --from "HEAD" --output "." (using from "HEAD" or from "BRANCHKEY" makes no difference)
- The package.xml wont have the added file
- 
## Execution context

---

![image](https://user-images.githubusercontent.com/1804862/133673031-6d955009-7eb8-4272-bbca-7a37a27fbbc9.png)

**Operating System:** It happens on Windows and on bitbucket docker container so the OS is no difference

**yarn version:** n/a

**node version:** 14.16

**git version:** 2.29.2.windows.3

**sfdx version:** 7.116

**sgd plugin version:** 4.8,1

## Optional more information

---

**Comment by fedegiust** [comment] 2021-09-16 19:27
List of commits with the added file

![image](https://user-images.githubusercontent.com/1804862/133673399-505911cb-15cf-4759-be24-049ab8d7ffeb.png)

package.xml missing the MultiMock apex class added 
![image](https://user-images.githubusercontent.com/1804862/133673420-d35a25c5-e673-4395-b273-38c96a98a895.png)

**Comment by scolladon** [comment] 2021-09-17 08:15
Hi @fedegiust !

Thanks for this bug, thanks for your contribution to make this plugin better !

First I can see the plugin version is not the latest.
Could you update the plugin and retry with the last version please ? (`sfdx plugins:update`)

Then, if the issue is still here, could you:

- clone the [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) (I gave you access to the repo)
- create a new branch (issue/199)
- make all the commits necessary to isolate the issue
- Let us know when done and give us the command to reproduce the issue

Thanks in advance, and happy to help

**Comment by scolladon** [comment] 2021-11-17 13:51
One month without moving forward on this one.
If you have any element to help reproducing and isolating the issue please raise your hand !

Else we will close this issue

**Comment by Ronak-Toshniwal** [comment] 2023-01-24 13:37
Hi [scolladon](https://github.com/scolladon)
can you please reopen i am also facing same issue
my PR has all the files but in pipe it is only getting files which are MODIFIED not newly created.

**Comment by scolladon** [comment] 2023-01-24 13:40
Hi @Ronak-Toshniwal 

Sure, let's reopen it.

Can you give use more information to reproduce the issue please
- What is the sgd version you are using ? (`sfdx plugins` output it)
- What commit should I do, on which metadata type ?
- What parameter I should pass to sgd to reproduce it locally

**Comment by Ronak-Toshniwal** [comment] 2023-01-24 14:30
remote: Permission to scolladon/sfdx-git-delta-reproduction-playground.git denied to Ronak-Toshniwal.

could you please give me permission getting the above error for new branch issue/190

**Comment by Ronak-Toshniwal** [comment] 2023-01-24 14:50
Hi 
In my pipelines i use npm install sfdx-git-delta@latest
so currently it is getting me version 5.7.0

<img width="112" alt="image" src="https://user-images.githubusercontent.com/73140231/214326399-6126d510-5191-4083-b36a-f3523d09cd2a.png">

Hope you approve my workflow request so it can run
https://github.com/scolladon/sfdx-git-delta-reproduction-playground/pull/6

**Comment by scolladon** [comment] 2023-01-24 19:20
Hi @Ronak-Toshniwal 

Let me know if I can help
If you manage to reproduce your issue, let me know

**Comment by Ronak-Toshniwal** [comment] 2023-01-25 06:09
Hi [scolladon](https://github.com/scolladon)

i am trying but not able to reproduce the issue in this repo.
but same thing still occuring for my repo
working to reproduce
can it be some issue with bitbucket?
or can be issue with below command?
`node_modules/sfdx-cli/bin/run sgd:source:delta --to "origin/${BITBUCKET_PR_DESTINATION_BRANCH}" --from "origin/${BITBUCKET_BRANCH}" --output changed-sources/ -i .sgdignore`

**Comment by scolladon** [comment] 2023-01-25 08:21
Hi @Ronak-Toshniwal 

Could you try with the `latest` version ? (`v5.11.1`) 
```sh
sfdx plugins:install sfdx-git-delta@latest
```

And also can you provide the bitbucket repository url ?
I'll try to have a look to the pipeline.

**Comment by Ronak-Toshniwal** [comment] 2023-01-25 08:35
Hi 
yes I am installing latest plugin with @latest tag but I can't share you link of the repo because it has confidential data.
if you want I can share pipeline code.

`
image: atlassian/default-image:3
#image: python

clone:
  depth: full


pipelines:
  pull-requests:
   '**': 
      - step:
          script:
            #Assign variables
            - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            - export SFDX_AUTOUPDATE_DISABLE=false
            - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
            - export SFDX_DOMAIN_RETRY=300
            - export SFDX_DISABLE_APP_HUB=true
            - export SFDX_LOG_LEVEL=DEBUG
            - export DEPLOYDIR=src 
            - export TESTLEVEL=RunLocalTests
            #Create sfdx directory
            - mkdir ~/sfdx
            #Install Salesforce CLI
            #By default, the script installs the current version of Salesforce CLI. To install the release candidate, set the DX_CLI_URL_CUSTOM local variable to the appropriate URL
            #- wget -qO- ${DX_CLI_URL_CUSTOM-$CLIURL} | tar xJ -C ~/sfdx --strip-components 1
            - npm install sfdx-cli
            - export PATH=~/sfdx/bin:$PATH
            - apt-get update 
            - echo y | apt-get install python3-pip
            - pip install yq
            - yq --version

            #Decrypt server key
            - openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            #Authorize target org
            - node_modules/sfdx-cli/bin/run  auth:jwt:grant --instanceurl $LOGIN_URL --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key --username $PROD_USERNAME --setalias PROD
            - echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
            - git fetch origin "+refs/heads/*:refs/remotes/origin/*"
            - echo -e '.github\n.sf\n.sfdx\n.vscode\n.config\nassets\nconfig\nnode_modules\nscript' > .sgdignore
            - mkdir changed-sources
            - node_modules/sfdx-cli/bin/run sgd:source:delta --to "origin/${BITBUCKET_PR_DESTINATION_BRANCH}" --from "origin/${BITBUCKET_BRANCH}" --output changed-sources/ -i .sgdignore
            - cat changed-sources/package/package.xml
            - dir changed-sources/

            
            - export APEX_CLASSES=$(xq . < changed-sources/package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | unique | join(",")' -r)
            - echo $APEX_CLASSES
            - echo "--- Delta Check-Only Deploy ---"
            - |
                echo "Runway Execution Step............"
                if [ -z "$APEX_CLASSES" ]; then 
                  echo y | node_modules/sfdx-cli/bin/run  force:source:deploy -x changed-sources/package/package.xml -w 30 -u $PROD_USERNAME -c
                else 
                  echo y | node_modules/sfdx-cli/bin/run  force:source:deploy -x changed-sources/package/package.xml -w 30 -l RunSpecifiedTests -r "$APEX_CLASSES" -u $PROD_USERNAME -c
                fi
                     

  branches:
   'master': 
      - step:
          script:
            #Assign variables
            - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            - export SFDX_AUTOUPDATE_DISABLE=false
            - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
            - export SFDX_DOMAIN_RETRY=300
            - export SFDX_DISABLE_APP_HUB=true
            - export SFDX_LOG_LEVEL=DEBUG
            - export DEPLOYDIR=src 
            - export TESTLEVEL=RunLocalTests
            #Create sfdx directory
            - mkdir ~/sfdx
            #Install Salesforce CLI
            #By default, the script installs the current version of Salesforce CLI. To install the release candidate, set the DX_CLI_URL_CUSTOM local variable to the appropriate URL
            #- wget -qO- ${DX_CLI_URL_CUSTOM-$CLIURL} | tar xJ -C ~/sfdx --strip-components 1
            - npm install sfdx-cli
            - export PATH=~/sfdx/bin:$PATH
            - apt-get update 
            - echo y | apt-get install python3-pip
            - pip install yq
            - yq --version

            #Decrypt server key
            - openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            #Authorize target org
            - node_modules/sfdx-cli/bin/run  auth:jwt:grant --instanceurl $LOGIN_URL --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key --username $PROD_USERNAME --setalias PROD
            - echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
            - node_modules/sfdx-cli/bin/run plugins 
            - git fetch origin "+refs/heads/*:refs/remotes/origin/*"
            - echo -e '.github\n.sf\n.sfdx\n.vscode\n.config\nassets\nconfig\nnode_modules\nscript' > .sgdignore
            - mkdir changed-sources
            - node_modules/sfdx-cli/bin/run sgd:source:delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta  -i .sgdignore
          
            - cat changed-sources/package/package.xml
            - dir changed-sources/

            #Deploy to target deployment org and run unit tests
            #- sfdx force:mdapi:deploy --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL
            #- echo y | node_modules/sfdx-cli/bin/run  force:source:deploy -x changed-sources/package/package.xml -u $PROD_USERNAME  -c
            #Example shows how to run a check-only deploy.
            #- sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVE



            - export APEX_CLASSES=$(xq . < changed-sources/package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | unique | join(",")' -r)
            - echo $APEX_CLASSES
            - echo "--- Delta Check-Only Deploy ---"
            - |
                echo "Runway Execution Step............"
                if [ -z "$APEX_CLASSES" ]; then 
                  echo y | node_modules/sfdx-cli/bin/run  force:source:deploy -x changed-sources/package/package.xml -w 30 -u $PROD_USERNAME 
                else 
                  echo y | node_modules/sfdx-cli/bin/run  force:source:deploy -x changed-sources/package/package.xml -w 30 -l RunSpecifiedTests -r "$APEX_CLASSES" -u $PROD_USERNAME 
                fi
  
  `

**Comment by scolladon** [comment] 2023-01-25 08:58
I think it could be because the commits are not locally available for git.
I can see there is a git fetch executed, and then sgd is used to compare current commit with previous commit

My assumption here is that the previous commit is not present in the history, it is only fetched as a ref.
You can test this hypothesis by doing a simple git diff just before using sgd: `git diff --name-status --no-renames "HEAD~1" "HEAD"` in the pipeline
If there is no output it means the previous commit are not loaded.
You could use a [clone step](https://support.atlassian.com/bitbucket-cloud/docs/git-clone-behavior/#Depth:~:text=full%20(for%20full%20depth)%20or%20any%20positive%20integer) to ensure having all the history.
Let me know if it helps

**Comment by scolladon** [comment] 2023-02-06 09:52
Closing this issue because of inactivity

If you are still blocked, reopen this issue with information allowing us to reproduce it please.
We will try our best to help you

**Closed by scolladon** 2023-02-06 09:52 UTC
Labels: bug, reproduction steps needed

**Comment by Shultsev13** [comment] 2024-11-29 10:42
Hi @scolladon 
Have similar problem with my Azure yml pipeline.
Tried to check hypothesis about "previous commit is not present in the history, it is only fetched as a ref"
This command `git diff --name-status --no-renames "HEAD~1" "HEAD"` returns 
![image](https://github.com/user-attachments/assets/e33b1313-98f8-4188-b15a-a48aab2edab1)
But this one `sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."` returns such output in file
![image](https://github.com/user-attachments/assets/9b1f905b-c855-4012-8d19-4e1b9331e33d)

Here is the part of pipeline that can be helpful
```jobs:
  - job: ValidateCode
    displayName: 'Validate Salesforce Code'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      RELEVANT_CHANGES_DETECTED: "false"
    steps:
      
      - checkout: self
        fetchDepth: 0

      - task: UseNode@1
        inputs:
          version: '18.x'
        displayName: 'Install Node.js'

      - script: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
        displayName: 'Install xmllint'

      - script: |
          npm install @salesforce/cli --global
          sf plugins install @salesforce/sfdx-scanner
          echo y | sfdx plugins:install sfdx-git-delta@latest
        displayName: 'Install Salesforce CLI and plugins'

      - script: |
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."
          echo "Changed files:"
          for file in $(find package -type f); do
            echo "File: $file"
            cat "$file"
            echo ""
          done
          if grep -q '<types>' ./package/package.xml ; then
            echo "##[section]Found changes to deploy"
            echo "##vso[task.setvariable variable=RELEVANT_CHANGES_DETECTED;]true"
          else
            echo "##[section]No changes to deploy"
          fi
        displayName: 'Get delta'

**Comment by scolladon** [comment] 2024-11-30 10:51
Hi @Shultsev13!

Sorry to see that.
From what I read it seems the pipeline is configured to fetch all the history.

I have couple questions though: 

Where the diff commands is ran ? (`git diff --name-status --no-renames "HEAD~1" "HEAD") On the CI ? Or on your machine ? If on your machine, have you tried to run it inside the CI ? What is the result on the CI ?

Does the metadata are directly at the root of the repository ? Or are they inside a `force-app` (or other) folder ?
If they are at the root, could you try to move them inside a force-app folder and retry your scenario please ?

Also, if all of those questions have not helped, could you help me reproduce the issue locally ?
You can either describe what commit content I should create inside a repository, or you could also fork the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground), create a branch, write the necessary commit to reproduce and share that branch here.
And give me the commands to run with sgd to reproduce the issue.

**Comment by Shultsev13** [comment] 2024-12-01 14:55
Both screenshots were taken from my local machine because I thought I didn't have enough knowledge of pipelines and it can be an issue. I'd run this command (sf sgd source delta --to "HEAD" --from "HEAD~1" --output ".") in pipeline and receive same set of files as on my local machine. I can also add this  (`git diff --name-status --no-renames "HEAD~1" "HEAD") to my pipeline, but assume that it will output all files same as one local machine. 

Metadata is located directly in the root folder. When I tried to move it to 'force-app' in the pipeline, nothing changed.

Not familiar with forking, so here are my steps that lead me to this issue:
1. First commit was with two Apex classes created, (custom labels were already created before)
2. Second commit was with two new LWC components plus custom labels and Apex classes was modified

If you can't reproduce this issue, can try to do a fork

**Comment by scolladon** [comment] 2024-12-01 16:08
Thanks for the update @Shultsev13 

> This issue is related to folder structure. When you have a standard force-app structure it works fine, but if folders like classes, aura, lwc, etc. are located in the root folder of your repo it doesn't add newly created files to package.xml. Is there is an option to fix this?

Yes ! You could put your metadata inside a "src" folder !
Unfortunately there is no option to fix that on sgd side unless changing the current code.
The plugin is compatible with sfdx source format structure and metadata (source format metadata contained inside a "src" folders. The "src" folder can be named `force-app` or something else, it does not matter).
The plugin expect this kind of folder structure and is designed and tested for that.

When the metadata are not in a parent folder then the plugin is not be able to detect the kind of metadata located inside folders (like `lwc component`, `aura component`, `static resources`, `experience sites`, etc). It is because those metadata are located inside a dedicated folder and its sub definition files can located inside sub folders. To make sure this is possible the plugin assume the type is not the root folder.
It could be fixed but I don't think it would be interesting because it is not an expected folder structure when dealing with sfdx source format.
