### ISSUE TITLE
When a flow metadata is changed and the translations isn't, all the translations for the new flow version are lost

### ISSUE THREAD

**Issue by ArielS1** [scolladon/sfdx-git-delta#321] opened 2022-07-31 07:48 UTC
## What is the problem?

---

When we change a flow metadata and don't make any change to the translations file, after the deploy we loose all the translations related to that flow.
The reason for this is that the translation for each flow is managed by a flow version, so if a flow is deployed without the translation file, then there are no translations for its new version.

## Steps to reproduce

---

1. Have an env with a flow with translations
2. Use sgd to produce a package that detects a change only in the flow so a package.xml file is produced without the translations file
3. After the package is deployed, the new flow version will loose its translations

## Current workaround

---

Every time we touch a flow metadata, we make a small insignificant change to the translation file too so it will also be added to the package.xml

## Solution suggestion

If a flow was added to to the package.xml file and a translation wasn't, then force add translations.
This functionality might also be activated by a flag in the cli or some kind of configuration

a more advanced solution is to check which specific file translation contains a reference to that specific changed flow instead of adding the entire translations directory

**Comment by scolladon** [comment] 2022-08-01 10:15
Hi @ArielS1 

Thanks for this awesome enhancement suggestion ! And thanks for your interest in the plugin and for your help to make it better

Here are the approached proposed (I agree with those):

- (A) Add translation when a flow is Updated or Added, do not treated Deleted event
- (B) _Improved version_ check if there is a reference to the flow in the translation file before adding it

Here are the way we can apply this behaviour:

- (A) Automatically and systematically (as we add the related object when a master detail field is added)
- (B) Using a CLI parameter (I don't really like it because it will be set most of the time from what I see, then we could have a CLI parameter to not apply the logic but it is hard to understand)
- (C) Using a config file (introducing `.sgdrc` per exemple).

My personal choice would be to go for (B) - (A)
- Add translation when flow is Updated or Added, if the flow is referenced in it.
- Automatically and systematically

@mehdisfdc I think we should talk about that in our next "copil"
In the meantime I can start a PR to add the translation when a flow is Updated or Added (first step)
Our decision here will need an ADR

**Comment by ArielS1** [comment] 2022-08-01 11:14
> translation

I also think that the param is not a must to have feature.

My initial idea was that projects that don't use translations would like to skip this functionality, but if we check for a reference to the flow in the translation file we make sure that it is a necessary functionality

**Comment by scolladon** [comment] 2022-08-01 11:30
You're right @ArielS1 

I'm going to create a branch on our [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) for reproduction and smoke testing the solution.

@ArielS1 could you provide us an exemple of:

- a template flow file, with name, path location, file version and simple content
- a template translation file, with name, path location and simple content (to see how xml tag referencing the flow version for translation)

It would really help us.
And also if you have time to help us in the QA it would be great (you'll be acting as our customer 😄)

**Comment by ArielS1** [comment] 2022-08-01 12:22
> You're right @ArielS1
> 
> I'm going to create a branch on our [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) for reproduction and smoke testing the solution.
> 
> @ArielS1 could you provide us an exemple of:
> 
> * a template flow file, with name, path location, file version and simple content
> * a template translation file, with name, path location and simple content (to see how xml tag referencing the flow version for translation)
> 
> It would really help us. And also if you have time to help us in the QA it would be great (you'll be acting as our customer 😄)

This is the metadata for the flow:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Flow xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>55.0</apiVersion>
    <interviewLabel>SGD {!$Flow.CurrentDateTime}</interviewLabel>
    <label>SGD Translation Bug Reproduction</label>
    <processMetadataValues>
        <name>BuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>CanvasMode</name>
        <value>
            <stringValue>AUTO_LAYOUT_CANVAS</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>OriginBuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processType>Flow</processType>
    <screens>
        <name>Screen_To_Translate</name>
        <label>Screen To Translate</label>
        <locationX>176</locationX>
        <locationY>158</locationY>
        <allowBack>true</allowBack>
        <allowFinish>true</allowFinish>
        <allowPause>true</allowPause>
        <fields>
            <name>Translated_Text</name>
            <fieldText>&lt;p&gt;This is the original text without a translation&lt;/p&gt;</fieldText>
            <fieldType>DisplayText</fieldType>
        </fields>
        <showFooter>true</showFooter>
        <showHeader>true</showHeader>
    </screens>
    <start>
        <locationX>50</locationX>
        <locationY>0</locationY>
        <connector>
            <targetReference>Screen_To_Translate</targetReference>
        </connector>
    </start>
    <status>Active</status>
</Flow>
```

it should be saved in: \force-app\main\default\flows\SGD_Translation_Bug_Reproduction.flow-meta.xml

this is the metadata for a German translation:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Translations xmlns="http://soap.sforce.com/2006/04/metadata">
    <flowDefinitions>
        <flows>
            <screens>
                <fields>
                    <fieldText>This is a the text translated to German</fieldText>
                    <name>Translated_Text</name>
                </fields>
                <name>Screen_To_Translate</name>
            </screens>
        </flows>
        <fullName>SGD_Translation_Bug_Reproduction</fullName>
    </flowDefinitions>
</Translations>

```

it should be saved in: \force-app\main\default\translations\de.translation-meta.xml

when you open the flow you will see a text in English in the screen:
"This is the original text without a translation"

when you open the flow while you change your user language to German you will see a translated text in the screen:
"This is a the text translated to German"

after you invoke sgd to touch the flow only and deploy the generated xml
the text "This is the original text without a translation" will be shown also on the German language, because the translations have been detached

**Comment by scolladon** [comment] 2022-08-01 12:47
Thank you very much for all those information.
I think I have everything I need to focus work.

Another workaround I see here would be to redeploy translations after deployment.
I think it would work
Even if it is less efficient than the workaround you proposed, it is simpler.
If you think too, could you edit your description to add it please ? Maybe it can suit other with smaller repository in the mean time

Thank you very much for your algorithm suggestion

> or maybe a more efficient way is when there are flow changes, save the flow api names in an array
then iterate each translation file, on each iteration make an iteration of that flows api names array, if one of those api names is found, add the translation file and break the inner loop

I will take inspiration from this

**Comment by ArielS1** [comment] 2022-08-01 13:09
> Thank you very much for all those information. I think I have everything I need to focus work.
> 
> Another workaround I see here would be to redeploy translations after deployment. I think it would work Even if it is less efficient than the workaround you proposed, it is simpler. If you think too, could you edit your description to add it please ? Maybe it can suit other with smaller repository in the mean time
> 
> Thank you very much for your algorithm suggestion
> 
> > or maybe a more efficient way is when there are flow changes, save the flow api names in an array
> > then iterate each translation file, on each iteration make an iteration of that flows api names array, if one of those api names is found, add the translation file and break the inner loop
> 
> I will take inspiration from this

I tried your workaround, but it doesn't work.
When i deploy the translation file itself as a standalone without the flow, it won't recreate the translations for that specific flow version
the deployment has to be done together in order for that to happen, in a similar way that you should retrieve an object/custom label/flow together with the translation file in order to retrieve that specific metadata translations

**Comment by scolladon** [comment] 2022-08-01 13:13
Interesting...

What was the command you used to deploy the translations ?
Were you using a package.xml ?

**Comment by ArielS1** [comment] 2022-08-01 13:15
I just deployed it directly from Illuminated Cloud in Intellij

**Comment by scolladon** [comment] 2022-08-01 13:20
Is there a log of the command line executed ?
I'm curious of the result of `sfdx force:source:deploy -p force-app\main\default\translations`

**Comment by ArielS1** [comment] 2022-08-01 14:36
> sfdx force:source:deploy -p force-app\main\default\translations
Still haven't brought back the flow version translations
```
PS D:\IdeaProjects\salesforce> sfdx force:source:deploy -p .\force-app\main\default\translations\de.translation-meta.xml
*** Deploying with SOAP API v53.0 ***
Deploy ID: 0Af3H00000lDIeKSAW
DEPLOY PROGRESS | ████████████████████████████████████████ | 1/1 Components

=== Deployed Source

 FULL NAME TYPE         PROJECT PATH
 ───────── ──────────── ─────────────────────────────────────────────────────────── 
 de        Translations force-app\main\default\translations\de.translation-meta.xml
Deploy Succeeded.
```

**Comment by scolladon** [comment] 2022-08-02 15:49
@ArielS1 implementation is going well.

I have some concerned though
I wonder if we should rebuild the translation file to contain only the translations for the flow in the change list (if the translation is not in the change list as well).
Or if we should just copy the translation file, as everything that is in it should be in the target org it should not fail the deployment. But it can make the deployment very very big for huge translations files.

It is pretty much the same behaviour as for permission set or profile, should we scope them ? or should we let them full ? This kind of debate.

What is your point of view for the translations?

**Comment by ArielS1** [comment] 2022-08-02 20:09
> @ArielS1 implementation is going well.
> 
> I have some concerned though I wonder if we should rebuild the translation file to contain only the translations for the flow in the change list (if the translation is not in the change list as well). Or if we should just copy the translation file, as everything that is in it should be in the target org it should not fail the deployment. But it can make the deployment very very big for huge translations files.
> 
> It is pretty much the same behaviour as for permission set or profile, should we scope them ? or should we let them full ? This kind of debate.
> 
> What is your point of view for the translations?

I have an org with a translation file that contains 9k lines
I checked a deployment with few custom labels, the translation file and 2 custom metadata type records took almost 1 minute, i'm not sure if it's too much or not

about your suggestion, i'm not sure if that's the way sgd works, from my understanding it only supposed to create a package.xml file and then we can do whatever we like with it.
I don't think that creating a new translation file is a thing that this project does, or maybe it does and i don't know.
if it DOES copy the metadata files to a directory, then it would be a good idea to include only the relevant changes only for the changed flows, just be advised that if the file actually changed, then all the file should appear.
It could also be a good idea to perform this logic for other stuff the changed in the translation file, regardless to flows to have faster builds with specific translation changes

**Comment by scolladon** [comment] 2022-08-03 07:50
The plugin already scope the Workflow files and CustomLabel when using the `--generate-delta` parameter.
It means it rebuild the Workflow file with only the content of what has changed in it.
This is something we do.

Scoping based on the content of the package.xml is nearly the same thing technically.
But it will be another feature.
We also have an ongoing PR about checking permission set and profile compliance with a package.xml. It is a new command.
It could be migrated into another parameter (`--scope-ppset`) to be used with the existing command instead.

How I will break down the work:

1. add translation to package.xml and the output dir when present and a flow is in the change list. scope the content of the translation file to the flow definitions if not present in the package.xml (will be done with the [current PR](https://github.com/scolladon/sfdx-git-delta/pull/322))
2. scope content of the translation file based on the package.xml (should be done in a next PR)
3. scope content of Profile & Pset based on the package.xml ([in progress in another PR](https://github.com/scolladon/sfdx-git-delta/pull/90), need refactoring to be included with a new parameter instead of a new comment)

**Comment by scolladon** [comment] 2022-08-06 23:38
Hi @ArielS1

The PR is going well, the state is pretty stable #322 

Could you test it in your conditions please ? (Here is the [guide](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) "how to do so")

**Comment by scolladon** [comment] 2022-08-26 07:20
Thank you very much @ArielS1 

New version [5.4.0](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.4.0) is just released with this enhancement !
Thanks for helping improving the plugin

Happy incremental deployment !!

**Comment by ArielS1** [comment] 2022-08-26 07:41
Hi,
I'm sorry I couldn't test it.
I tried to do it, but I'm not so familiar with sfdx plugins, since it's used only by the pipeline the devops created at my org
I had issues to use the branch with the feature on my local pc

**Comment by scolladon** [comment] 2022-08-26 07:47
No problem, we did the maximum QA we could on our side (with the [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/321) and our special monstruous org) and we were pretty confident.

**Comment by ArielS1** [comment] 2023-11-02 13:01
Hi,

I used in my org version 5.24.2 and this feature was working fine.
I upgraded the rep version to 5.27.0 to be able to use apiversion 59.0, but since then this feature stopped working.
Was anything changed about this feature?
Is there maybe a new cli param that i need to include to make it work?

Thanks

**Comment by ArielS1** [comment] 2023-11-02 14:52
> Hi @ArielS1,
> 
> I'm very sorry to hear that. We may have introduce a regression from what you are experiencing.
> 
> Could you tell me how to reproduce the issue locally please?

Whenever you make a change to a flow that one of the translation files references it, the translation file will be included in the package.xml even if that translation file wasn't changed.

that was the feature
so to reproduce it:
1. add a reference to a flow in a translation file
2. change a flow, without changing the translation file
3. you will notice the translation file was not added to the package.xml

**Comment by scolladon** [comment] 2023-11-03 14:44
Hi @ArielS1 

I tried locally using the latest version of the plugin (currently `5.27.0`) and I was not able to reproduce the issue following the steps to reproduce.
Meaning it worked on my local.

Everything is accessible in our reproduction playground with the branch `[issue/321](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/321)`.
Could you do 2 things for us please?
1. try to reproduce the issue with the reproduction playground
	- clone the reproduction playground: `git clone git@github.com:scolladon/sfdx-git-delta-reproduction-playground.git && cd sfdx-git-delta-reproduction-playground`
	- checkout the `issue/321` branch: `git checkout issue/321`
	- run sgd: `sfdx sgd:source:delta --from HEAD~1 -d` (the last commit is a flow modification. This flow has translation in multiple translation files)
	- check the `package.xml` content: On my laptop it is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>SGD_Translation_Bug_Reproduction</members>
        <name>Flow</name>
    </types>
    <types>
        <members>de</members>
        <members>en</members>
        <name>Translations</name>
    </types>
    <version>50.0</version>
</Package> 
```
2. Downgrade the plugin on your laptop to version `5.24.2` (sfdx plugins:install `sfdx-git-delta@5.24.2`) and try to reproduce the issue you have with version `5.27.0` in your repository. Let us know the result please.

**Comment by scolladon** [comment] 2023-12-19 08:48
Hi @ArielS1 

Any update on this one ?
If you managed to solve it could we close this issue ?

**Comment by scolladon** [comment] 2024-01-30 14:05
Closing this issue

Feel free to reopen it with more information

**Comment by ArielS1** [comment] 2024-08-11 13:41
> ## What is the problem?
> When we change a flow metadata and don't make any change to the translations file, after the deploy we loose all the translations related to that flow. The reason for this is that the translation for each flow is managed by a flow version, so if a flow is deployed without the translation file, then there are no translations for its new version.
> 
> ## Steps to reproduce
> 1. Have an env with a flow with translations
> 2. Use sgd to produce a package that detects a change only in the flow so a package.xml file is produced without the translations file
> 3. After the package is deployed, the new flow version will loose its translations
> 
> ## Current workaround
> Every time we touch a flow metadata, we make a small insignificant change to the translation file too so it will also be added to the package.xml
> 
> ## Solution suggestion
> If a flow was added to to the package.xml file and a translation wasn't, then force add translations. This functionality might also be activated by a flag in the cli or some kind of configuration
> 
> a more advanced solution is to check which specific file translation contains a reference to that specific changed flow instead of adding the entire translations directory

I think the feature that should add the translation file when there is an existing translation to the changed flow has stopped working at some point.
Or is there i configuration or a specific flag i should use in order to make it work?

**Comment by scolladon** [comment] 2024-08-11 13:49
Hi @ArielS1 

Sorry to ear you still have issue with this feature.
What is the context of execution ? (`uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins`)
How should I reproduce it ? Is there something different than from the steps explained here ?

**Comment by scolladon** [comment] 2024-08-13 16:51
Hi @ArielS1,

I tried to reproduce it on my laptop without success.
I put everything in the branch [issue/321](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/321) of the reproduction playground, based on the information you provided.

Do you reproduce the issue on your local ?
Are you sure the plugin version used inside jenkins is v5.40.2 ?

**Comment by ArielS1** [comment] 2024-08-13 18:31
> Hi @ArielS1,
> 
> I tried to reproduce it on my laptop without success. I put everything in the branch [issue/321](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/321) of the reproduction playground, based on the information you provided.
> 
> Do you reproduce the issue on your local ? Are you sure the plugin version used inside jenkins is v5.40.2 ?

I'm 100% sure this is the version
It's in the Jenkins console log and we recently upgraded to this version because of something new that wasn't detected on an older version.

I'll try to do it on my local tomorrow.
But isn't there a flag or a configuration to enable this feature?

**Comment by scolladon** [comment] 2024-08-13 18:42
No flags for this feature, it is enabled by default

**Comment by ArielS1** [comment] 2024-08-14 15:21
When i created a local git repository i managed to reproduce the problem with the real files
When i forked the playground it worked as expected

So i think it's something with the translations file.
i pushed the real flow and the real translations file, but now i can't run the command, i'm getting the following error:
$ sfdx sgd:source:delta --to "master" --from issue/321 --repo . --output .
(node:29924) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "error": "--to is not a valid sha pointer: 'master' (If in CI/CD context, check the fetch depth is properly set)",
  "output": ".",
  "success": false,
  "warnings": []
}

I'm not familiar with the meaning of the error, maybe you know better how to fix it, i think it can reproduce the problem if it will run.

here is the repository:
https://github.com/ArielS1/sfdx-git-delta-reproduction-playground/tree/issue/321

**Comment by ArielS1** [comment] 2024-08-14 17:25
I tried to run the command with main like you suggested, but sfdx stopped working:
PS C:\Users\arielsi\IdeaProjects\sfdx-git-delta-reproduction-playground> sfdx sgd:source:delta --to main --from issue/321 --repo . --output .                              
'"C:\Users\arielsi\AppData\Local\sfdx\client\bin\..\7.209.6-8ba3197\bin\sfdx.cmd"' is not recognized as an internal or external command,
operable program or batch file.

i use windows
sfdx version i'm not sure, since it died
node v16.16.0
my forceignore doesn't include translations

tomorrow i'll try to fix sfdx and create my own github repository where the issue is reproduced

**Comment by ArielS1** [comment] 2024-08-15 07:24
I managed to reproduce it here:
https://github.com/ArielS1/SgdFlowTranslations

this is the command i invoked:
sgd:source:delta --to master --from changeFlow --repo . --output .

git version 2.33.0.windows.2
node version: v20.16.0
sf version: @salesforce/cli/2.53.6 win32-x64 node-v20.15.1
sf plugins: sfdx-git-delta 5.42.0

**Comment by ArielS1** [comment] 2024-08-15 07:33
I don't think it has anything to do with the content of the flow and translation files
when i create a fresh project the problem is reproduces
when i fork it from the playground repo it doesn't
it feels to me that the problem happens because of some other file, or a lack of a file or a configuration that exists on the playground repo

**Comment by scolladon** [comment] 2024-08-15 17:17
Hi @ArielS1 
Thanks to your reproduction playground I have been able to reproduce the issue.
The issue is because the plugin is looking for translation file ending with `-meta.xml` suffix (ex: `iw.translation-meta.xml`).
I'll ship a fix soon so it can take in consideration file ending with `translation` or `translation-meta.xml`.

Stay tuned

**Closed** 2024-08-26 10:32 UTC
Labels: enhancement, good first issue, reproduction steps needed

**Comment by ArielS1** [comment] 2024-08-27 07:34
Hi again,

I think i found another issue with this feature.
1. Somebody open a PR and touched a flow that is referenced in a translation, a package.xml was generated with the flow and the translation - that's ok
2. Since the build failed, i decided to remove all the references to the flow inside the translation file, they were redundant anyway, i did it using a different branch and a different PR.
3. I came back to the original PR and invoked the command again, i didn't update the branch with the changes of the translation file, but the change existed on the target branch, but the package.xml was generated with both the flow and the translation file
since i removed the references to the flow in the translation file, i expected the translation not to appear in the generated package.xml
so the translation file was deployed while it was not necessary.

The issue:
It seems that when the code that searches for the references of the flow inside the translation files it happens on the origin branch, and not the target branch, i think it should be the opposite, since the target branch is the final outcome

**Comment by scolladon** [comment] 2024-08-27 09:09
Interesting @ArielS1, could you send a reproduction scenario (using the playground would be best) with all the steps and the commands used please ?

**Comment by vimal-varghese** [comment] 2025-02-28 20:56
Hello @scolladon, 
We are using SGD v5.49 along with SF CLI v2.62.6 on node v20.17.0 and encountered the same issue as described in the Problem statement of the issue.

As a workaround, we have decided to deploy the entire Translations file along with the problematic flow, which is missing the translation on the new version.

Thanks,

Vimal Varghese

**Comment by scolladon** [comment] 2025-02-28 21:09
Hi @vimal-varghese 

Do you have the issue with the latest v6 version ?

**Comment by vimal-varghese** [comment] 2025-02-28 21:32
We may need to upgrade our plugin to version 6 in our pipeline to confirm, Sebastien.  I will confirm you in the upcoming weeks, if version 6 has resolved this problem.

Thank you

**Comment by vimal-varghese** [comment] 2025-03-05 00:38
Hello @scolladon, 
This is just to confirm, the above reported problem persists on **SGD version 6.3.0** as well with **SF CLI version 2.78.3** and **node version 22.14.0**.

Flow metadata has new changes, hence the SGD plugin is fetching the required Flow metadata as expected into the delta package. However, the French translation metadata do not have changes associated with the Flow for the current release, hence the French Translation metadata fetched by SGD do not contain the required Flow definition translations block of code, Therefore, the new Flow version is missing the translations after deployment.

Thanks,
**Vimal Varghese**

**Comment by scolladon** [comment] 2025-03-05 08:39
Hi,

I just checked with a quick unit test and with our e2e test and with what I have tested it seems to work...

1/ Does the translations are in the git repository?
2/ Does the translations are not in the `.sgdignore` file?

If both the answers are no, could you help me reproduce on my machine please?
You can either describe what commit content I should create inside a repository, or you could also fork the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground), create a branch, write the necessary commit to reproduce and share that branch here.
And give me the commands to run with sgd to reproduce the issue.
