### ISSUE TITLE
Test classes are missed

### ISSUE THREAD

**Issue by ena9** [scolladon/sfdx-git-delta#780] opened 2024-02-02 11:37 UTC
when I want to create destructiveChanges.xml file, there is no Apex test class in it, although they should be there

**Comment by scolladon** [comment] 2024-02-02 11:50
Hi @ena9!

Thanks for raising this issue and thanks for contributing in making this project better!

Can you please tell me more about it ?
What is the environment ? (Os, git version, node version, sfdx version, sgd version)
How can I reproduce the issue locally (step by step) ?

**Comment by ena9** [comment] 2024-02-02 13:29
I tried to reproduce it one more time, and maybe you could please tell me what I'm doing wrong.
1. created a new xxxx branch from a development branch
2. created new apex classes
3. added commit to the branch
4. checked out to the development branch
5. run in the terminal "sfdx sgd:source:delta --to development --from update_jira_records --output ."

 result in the attached screenshot

<img width="2013" alt="image" src="https://github.com/scolladon/sfdx-git-delta/assets/26391142/77bcef3f-8217-486a-a1bc-d3896e42886e">

**Comment by scolladon** [comment] 2024-02-02 13:35
Do the changes made in the new branch are committed ?
I think you should invert `from` and `to` parameters as well. [Because](https://github.com/scolladon/sfdx-git-delta?tab=readme-ov-file#use-cases) the oldest branch in this case is the `development` branch I guess.

**Comment by ena9** [comment] 2024-02-02 13:36
yes,  changes are committed

**Comment by ena9** [comment] 2024-02-02 13:37
i tried to invert from and to parameters. it doesn't work for me

**Comment by scolladon** [comment] 2024-02-02 13:40
What version of the plugin are you using ?

I see the classes are not in a `classes` folder. 
Meaning the plugin in the latest version is not able to recognize their type.
Two choices:
- you use latest-rc instead of latest
- you move the classes inside a classes folder

**Comment by ena9** [comment] 2024-02-02 13:54
yes, the reason for this issue is that I use a custom folder structure for the classes
thank you

**Comment by scolladon** [comment] 2024-02-02 13:58
Do you think I can still help ?
Or should we close this issue ?

**Comment by ena9** [comment] 2024-02-02 14:01
thank you for the support.
you can close the issue

**Closed** 2024-02-02 14:02 UTC
Labels: bug, reproduction steps needed
