### ISSUE TITLE
Addon Compatibility with Windows Salesforce CLI

### ISSUE THREAD

**Issue by ashishshukla38** [scolladon/sfdx-git-delta#92] opened 2021-01-19 12:07 UTC
Issue verification check :

[] Is current package working in Salesforce CLI within windows? 

## What is the problem
I have installed the latest version of SFDX from below URL:
https://developer.salesforce.com/tools/sfdxcli

But it shows latest node version as v12.18.3: 
sfdx-cli/7.84.2-a2868a68d5 win32-x64  node-v12.18.3

I separately installed nodeJS latest version globally. Then also Salesforce CLI refers the   node-v12.18.3, which is available under the Salesforce CLI folder. 

Any workaround or suggestion will be helpful to us. So, we can use the addon in windows Salesforce CLI.

---

_(Write your answer here.)_

### What is parameter and their value you used

_(Write your answer here.)_

### What is the expected result

_(Write your answer here.)_

### What is the actual result

_(Write your answer here.)_

## Steps to reproduce

---

_(Write your answer here.)_

## Execution context

---

**Operating System:** …

**Yarn version:** …

**Node version:** …

**sgd version:** …

**SDK Version:** …

## Optional more information

---

_(Write your answer here.)_

**Comment by scolladon** [comment] 2021-01-19 12:51
Hi @ashishshukla38 !

If I understand well, executin the CLI sfdx on windows seems to use the inner sfdx node installation (v12) instead of the node version installed in the local machine even if there is a local node version installed on the machine right ?

If then, it looks like an [issue with the CLI](https://salesforce.stackexchange.com/questions/331574/node-version-error-during-salesforce-dx-pre-release-plugin-installation) itself...

Could you fill the PR with Execution context information please ?

**Comment by mehdisfdc** [comment] 2021-01-19 12:55
This looks like a duplicate of https://github.com/scolladon/sfdx-git-delta/issues/85

Node v14.6.0 or above is required for the SGD plugin.

The current Salesforce CLI installer comes with node v12, which cannot be used with SGD, so until the Salesforce CLI is upgraded with a more recent version of node, you will have to [install the Salesforce CLI via npm](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_npm).

**Closed by mehdisfdc** 2021-01-19 12:55 UTC
Labels: bug

**Comment by ashishshukla38** [comment] 2021-01-19 15:58
Thanks a lot @scolladon and @mehdisfdc for your quick response. We will try the following steps mentioned by @mehdisfdc .

**Comment by kknapp1** [comment] 2021-01-19 18:36
Thanks for the tip @mehdisfdc ! I was having the same issue. Completely uninstalling the Windows version and the npm version, then reinstalling only via npm resovled the issue for me.
