### ISSUE TITLE
Workflow Email Update deletion shows up in constructive and destructive package.xml

### ISSUE THREAD

**Issue by jayayy** [scolladon/sfdx-git-delta#300] opened 2022-05-05 09:42 UTC
Issue verification check:

- is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?
yes
## What is the problem?

---
Preface: We have configured different pipelines for constructive and destructive, respectively. I use an if command to see the third line of the package.xml and if it ends in version tag, we skip the deployment. 
On deleting the email alert metadata from a workflow, the workflow shows up in constructive and destructive package as well.  I am not sure if this is an expected behavior or a bug? It specifically picked the change as a workflowAction (ref. img 2) and then destructively deployed it. Whereas in the constructive package, it got validated successfully but then failed (ref. img 1). 
![image](https://user-images.githubusercontent.com/87470487/166896380-2225e42d-242e-4c32-a336-9df3c8fa71a2.png)
img 1
![image](https://user-images.githubusercontent.com/87470487/166896427-c21ddbcb-762e-4ca1-a918-4e3c6baae6b8.png)
img 2
![image](https://user-images.githubusercontent.com/87470487/166905716-be234aa6-2beb-4225-8b1a-b156f66d94bc.png)
Constructive package.xml
### What is the parameter and the value you used with it?

sfdx sgd:source:delta --output ./ --source=force-app/main/default/ --to HEAD --from ***

*** being the Last Successful Commit ID

### What is the expected result?

To either have the constructive package.xml empty or to not fail.

### What is the actual result?

Failure in constructive deployment; should only see changes in workflow file for constructive package.xml

## Steps to reproduce

---

Delete a workflow action eg email alert or field update 

## Execution context

---

**Operating System:** Ubuntu 20.04.4

**yarn version:** v1.22.18

**node version:**16.15.0

**git version:** 2.36.0

**sfdx version:** 7.143.0

**sgd plugin version:** 5.2.0

**Comment by jayayy** [comment] 2022-05-05 11:13
I think we have this resolved but do let me know your thoughts on this

**Comment by scolladon** [comment] 2022-05-05 11:50
Hi !

Thanks for raising this issue, and thanks for your help making the plugin better!

I'm not sure to understand properly the steps here.
What I think you are doing is the following:

1. Remove Workflow Alert Email (It is a change in the WorkFlow file, not a deletion)
2. Execute SGD => It generates a `destructiveChanges.xml` with the removed Workflow Alert Email And a `package.xml` with the Workflow (as the files is "changed")
_This is when I start to be a little bit lost_
3. Deploy destructive change => it deletes Workflow Email Alert
4. Validate generated package.xml with HEAD version of the repo => it passes, ok...
5. Deploy package.xml with HEAD version of the repo => it fails because there is a Rule using the deleted Workflow Email Alert... Which makes me wondering why the deployment of the `destructiveChanges.xml` has been able to deploy 🤔 and why the validation passed 🤔...

Could you shade some light here ?

Also if you could tell us the minimal steps to reproduce it on our end it would be very helpful.

This aside I think you may have a point here which is : The package.xml should not contains the Workflow if there is no related sub workflow metadata in it, isn't it?
I don't remember why we added this, probably because it fixes a deployment issue in the past with workflow using `package.xml` (maybe @mehdisfdc you remember it)
I wonder if your workflow would work if you use the [`-d`](https://github.com/scolladon/sfdx-git-delta#generate-a-folder-containing-only-the-addedmodified-sources) sgd parameter and use `sfdx force:source:deploy -p output/source/path` instead of `-x` ?

**Comment by jayayy** [comment] 2022-05-06 08:20
Well, diving deeper into this, I found that it was a developer's mistake that he didn't delink the workflow action. not sure if i am using the right terms but hope I can explain it. Once they deleted the workflow action (deletion of workflow action -> destructive change) and unlinked that action from the workflow (update on workflow file -> constructive change), both should run and it was expected behavior. I guess that is the reason you might have added it, not entirely sure about it tho. 

This brings me to another unrelated idea: Is there a common mistakes document when it comes to changes in SFDX format? Because with such a document, we can make sure there are no syntactical or metadata alignment issues. Would be great if you could point me to some resources. 

Thanks again

**Comment by scolladon** [comment] 2022-05-06 09:08
Thanks for the explanation!

Glad to hear it is fixable on your side.
If it is ok, I think we can close this issue, if the empty change workflow added in package.xml issue comes back for you or someone else we will consider modify the current behaviour.

Coming back to your unrelated idea 😄 
Such a document would be a goldmine, I actually do not have it or do not know if it exists. So far I think it is just the experience that build such knowledge, at least this is what I saw on the different project I worked on.
Maybe you should build it and expose it on github so you can maintain it and encourage community to participate!

**Closed by scolladon** 2022-05-06 09:08 UTC
Labels: bug
