### ISSUE TITLE
Issue with plugin-generating Incremental folder 

### ISSUE THREAD

**Issue by sairohith1009** [scolladon/sfdx-git-delta#438] opened 2023-01-30 14:18 UTC
Using "sfdx sgd source delta" with -d option to generate delta files in [--output] folder,
a delta containing some Apex classes was discovered,
the delta folder was created, but it contained only one apex class.
the package was populated correctly but the other apex class files was missing.

I have multiple commits 
**HEAD**           Commit1           Commit2           Commit3               **Commit4**
I want to compare and generate delta folder by comparing HEAD & commit4 in the above scenario.

**What is the parameter and the value you used with it?**

$ mkdir -p Delta_pkg/
$ sfdx sgd:source:delta -t HEAD -f Commit4 --output "Delta_pkg/" --generate-delta

**What is the expected result?**

I was expecting the delta_folder was containg also the following:
force/app/main/default/classes/Vis_Us_DataChangeRequestCtrl_Test.cls
force/app/main/default/classes/Vis_Us_DataChangeRequestCtrl_Test.cls-meta.xml
force/app/main/default/classes/AccountResource.cls
force/app/main/default/classes/AccountResource.cls-meta.xml

**What is the actual result?**

the output of the pipeline is 
force/app/main/default/classes/Vis_Us_DataChangeRequestCtrl_Test.cls
force/app/main/default/classes/Vis_Us_DataChangeRequestCtrl_Test.cls-meta.xml

**Operating System:**windows server 2016 standard

**node version:**v10.16.3

**git version:**2.22.0.windows.1

**sfdx version:** sfdx-cli/7.182.1 win32-x64 node-v18.12.1

**sgd plugin version:** v5.11.1

**Comment by scolladon** [comment] 2023-01-30 14:35
Also, we just deployed a `latest-rc` (`v5.11.3`) with a fix related to windows.
Could you try using this new version and see if it fixes your issue as well ?

You can install it via those two methods:
```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
$ sfdx plugins:install sfdx-git-delta@v5.11.3
```

**Comment by TJAlmn** [comment] 2023-01-30 16:40
I was currently experiencing the same issue. Upgrading it to newest version seemed to fix the error on Windows; however, I have some png file types that are generated through my deltas, and this process is corrupting such images.
This I'm experiencing not only on Windows, but Mac and Linux as well.

**Comment by scolladon** [comment] 2023-01-30 17:08
Hi @TJAlmn!

Thanks for the feedback, that's good news.

Could you give a bit more detail about the image corruption issue you are experiencing ?
Is it the case with any image ?
How can I reproduce it locally ?

**Comment by TJAlmn** [comment] 2023-01-30 19:04
@scolladon in order to create styling on the webpage, I use npm to generate a .css file with all the styling. After that is compiled, I run the sgd:source:delta with --generate-delta, but the delta file generated doesn't contain this .css file. And apart from that, PNGs and GIFs image formats get corrupted; so, as a result, the webpage styling doesn't display properly and images from those filetypes don't load at all.

CSS file is not corrupted, just doesn't get included in the delta file at all.

**Comment by scolladon** [comment] 2023-01-30 19:27
Ok, @TJAlmn.
I think you can use the `v5.8.0` (or the `stable` channel), it will work.

If the generated `.css` are not committed they will not be part of the diff.
Starting `v5.10.1` the file copied are taken from git and not from file system.
We are not going back to use the filesystem to generate delta output so I suggest you adapt your script by either committing its output or copy the generated files in the delta folder as well. 

@TJAlmn could you open a new issue for the corrupted binary file issue please ?

I'm closing this issue as the `latest-rc` fixes it and will be promoted `latest` soon

**Closed by scolladon** 2023-01-30 19:27 UTC
Labels: bug, reproduction steps needed

**Comment by sairohith1009** [comment] 2023-01-31 04:10
@scolladon Can i compare two branches directly instead of commit i'ds and generate the output folder ?

**Comment by scolladon** [comment] 2023-01-31 10:28
@sairohith1009 yes !

You can use any git commit pointer
- Commit SHA
- Branch name
- Tag
- Git expression

**Comment by sairohith1009** [comment] 2023-01-31 11:44
Thank you @scolladon 

I have tried this using the below 2 commands
$ sfdx sgd:source:delta -t develop1 -f origin/master --output "Delta_pkg/" --generate-delta

$ sfdx sgd:source:delta -t origin/develop1 -f origin/master --output "Delta_pkg/" --generate-delta

The output is same for both the commands:

 + mkdir -p Delta_pkg/

[Pipeline] sh
+ sfdx sgd:source:delta -t develop1 -f origin/master --output Delta_pkg/ --generate-delta

{
  "error": "--to is not a valid sha pointer: 'develop1'",
  "output": "Delta_pkg/",
  "success": false,
  "warnings": []
}

**Comment by scolladon** [comment] 2023-01-31 11:52
@sairohith1009 could you share the repository where I could reproduce this ? 

In which context do you have this behaviour ? In pipeline or locally ? If in pipeline could you share the pipeline definition file ?

**Comment by sairohith1009** [comment] 2023-01-31 11:57
@scolladon Sorry, the repo was my clients repo.

i'm executing the command in pipeline.
[delta jenkins file.txt](https://github.com/scolladon/sfdx-git-delta/files/10546094/delta.jenkins.file.txt)
this is script which i'm using to get the delta changes.

**Comment by scolladon** [comment] 2023-01-31 12:50
Usually in pipeline the [checkout step fetch only the last commit](https://github.com/scolladon/sfdx-git-delta#cicd-specificity).
It is possible to tell the checkout step to get more commit but it should be declared by the pipeline definition. Most of pipeline vendors provide mechanism to do so.

@sairohith1009 can you share the part of the pipeline where you checkout the repo ? I want to check if the checkout step get the whole repo content and not just the tip of the branch

**Comment by sairohith1009** [comment] 2023-01-31 13:00
@scolladon please find the attached file.
[delta jenkins file.txt](https://github.com/scolladon/sfdx-git-delta/files/10546560/delta.jenkins.file.txt)

**Comment by scolladon** [comment] 2023-01-31 14:39
It seems to be jenkins file, sorry @sairohith1009 but I'm not familiar with jenkins.
If you can reproduce on your local computer let me know how and I'll investigate.

This kind of issue in pipeline usually comes from the [repository fetch depth](https://github.com/scolladon/sfdx-git-delta#cicd-specificity).
You can check the repo is properly fetched by running this kind of commands in the pipeline context:
```sh
$ git show <remote>/<branch>
$ git show <local-branch>
# with develop1
$ git show origin/develop1
$ git show develop1
```

**Comment by scolladon** [comment] 2023-02-01 09:05
Hi @sairohith1009 when I run this kind of command on my repos it works fine.

Can you give me access to a repo where you reproduce the issue and tell me what command I should run to be able to reproduce the issue on my local machine please ?

**Comment by sairohith1009** [comment] 2023-02-01 09:10
Hello @scolladon 

I'm executing this commands in Jenkins and also in VS code
$ echo y | sfdx plugins:install sfdx-git-delta
$ mkdir -p Delta_pkg/
$ sfdx sgd:source:delta -t HEAD -f afc1b61590167f736e40258b21bb345f800ff124 --output "Delta_pkg/" --generate-delta

these are the commands which I'm executing in Jenkins and VS code

**Comment by scolladon** [comment] 2023-02-01 09:14
On my repos, on my machine, this command run fine.

Can you give me access to a repository where I can execute the command you gave to reproduce the issue ?

Also, what is the environment where you have this issue ? Windows/Unix, git version, node version, sfdx version, sgd version

**Comment by sairohith1009** [comment] 2023-02-01 09:31
@scolladon could you please share your mail i'd so that we can connect

**Comment by scolladon** [comment] 2023-02-01 10:16
@sairohith1009 let's get in touch on [gitter](https://gitter.im/) ?
You can find me with my github username (scolladon)
