### ISSUE TITLE
--ignore-whitespace ignores everything instead

### ISSUE THREAD

**Issue by 1ktribble** [scolladon/sfdx-git-delta#262] opened 2022-03-14 16:23 UTC
Issue verification check :

- [x] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem
---

When `--ignore-whitespace` is included in the sgd plugin command, it consistently presents an empty package.xml file. Remove that flag from the script adds all the correct items back to the package.xml file. I've verified the code, and there are additional changes outside of whitespace differences that are included in the git diff, but not included in the sgd package.xml creation.

### What is parameter and their value you used

Correct package.xml with members and names: `sfdx sgd:source:delta --to HEAD --from main --output .`
Incorrect package.xml with no types, members or names: `sfdx sgd:source:delta --to HEAD --from main --output . --ignore-whitespace`

### What is the expected result

```<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account.Name</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Account-Account Layout</members>
        <name>Layout</name>
    </types>
    <version>54.0</version>
</Package>
```

### What is the actual result

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>54.0</version>
</Package>
```

## Steps to reproduce

---

Run the command: `sfdx sgd:source:delta --to HEAD --from main --output . --ignore-whitespace`

## Execution context

---

sgd plugin version 5.0.0
git version 2.32.0

**Operating System:** Linux and MacOS

**yarn version:**1.22.10

**node version:**n/a, using sfdx plugin

**git version:** 2.32.0

**sfdx version:** 7.130.1

**sgd plugin version:** 5.0.0

## Optional more information

---
n/a

**Comment by scolladon** [comment] 2022-03-14 18:07
Hi @1ktribble !

Thanks for raising this issue and sorry for the inconvenience.
I hope working without the `-W` is okay for you until we fix this.

Good news !
I have been able to reproduce it!
I think it is linked to this PR #185 

I need more information from you:
Could you give use the content of those files in your repository:

- .gitattributes
- .git/config

Thanks in advance

**Comment by 1ktribble** [comment] 2022-03-14 18:48
We currently don't have a .gitattributes file setup in our repo.

Below is a replica of our .git/config
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
	quotepath = off
[remote "origin"]
	url = git@github.com:EnterpriseProd/gh-enterprise-salesforce.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[branch "feature/sfdc-11017-case-management"]
	remote = origin
	merge = refs/heads/feature/sf-11017-case-management
```

**Comment by scolladon** [comment] 2022-03-15 17:55
Hey,

Multiple forces are playing here, I have been able to reproduce the issue locally.

First, It seems [git diff --name-only with ignore space seems to be broken](https://stackoverflow.com/questions/61639191/git-diff-name-only-with-ignore-space-seems-to-be-broken)
Meaning we need to specify a `--word-diff-regex`. (The [default in the source code](https://stackoverflow.com/questions/30428377/what-are-git-diff-word-diff-default-regexps) is : `|[^[:space:]]|[\xc0-\xff][\x80-\xbf]+`)
Impact is we could not rely on the `.gitattributes` nor `.git/config` of the repo where the command is run.

Second, it seems `--name-status` ignore `--word-diff-regex`.
Meaning the command will consider white char anyway to generate `package.xml` and `destructiveChanges.xml`
This means it will only be considered when generating the delta file for InFile metadata type (like Workflows).

**Solutions**
For the first point we need to set `--word-diff-regex` with this value `|[^[:space:]]|[\xc0-\xff][\x80-\xbf]+`

For the second point we could:
- Switch to `--stat` git diff option instead of `--name-status`. 
=> Needs a refactoring in the way we parse a git diff line. 
It will have no impact on performance

- Keep name status without git diff `--word-diff-regex` and for each file do a file git diff with `--word-diff-regex` to filter them if they do not contains anything
=> Need a few line of code more in the filtering part of the code
It will have a big impact on performance because we will read every files 🤯 


**How to reproduce the analysis:**
Create a `Test` apex class, save it and commit it
Create a line break in Test.cls and save it
Change the content Test.xml and save it
Commit those 2 files

`git diff --word-diff-regex="|[^[:space:]]|[\xc0-\xff][\x80-\xbf]+" "HEAD~1" HEAD` shows diff for Text.xml only => Work as expected

`git diff --names-status --word-diff-regex="|[^[:space:]]|[\xc0-\xff][\x80-\xbf]+" "HEAD~1" HEAD` shows diff for Text.cls and Test.xml => Not what we wanted

`git diff --word-diff-regex "HEAD~1" HEAD` does not show anything (the original bug, because we do not set the regex)
`git diff --name-status --word-diff-regex "HEAD~1" HEAD` does not show anything (the original bug, because we do not set the regex)

**How to fix this**
I would tend to do it in two times:
1. _(Quick win)_ Fix the regex part of the git command by setting it to `--word-diff-regex="|[^[:space:]]|[\xc0-\xff][\x80-\xbf]+"` 
2. _(Requires spiking, refactoring and testing)_ Use `--stat` instead of `--name-status` so `--word-diff-regex` is applied correctly.

@mehdisfdc let's talk about it after a good night sleep on my side 😃

**Comment by scolladon** [comment] 2022-03-18 14:08
Version [5.0.3](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.0.3) is released with the fix @1ktribble !
Enjoy !
Reopen this issue if you think it is not yet fixed

**Comment by 1ktribble** [comment] 2022-03-18 14:45
Thanks 👍🏿

**Comment by 1ktribble** [comment] 2022-03-18 19:03
> Thanks 👍🏿

Looks like the issue is still present:

`Installing plugin sfdx-git-delta... installed v5.0.3`

```
\e[36mpackage.xml\e[0m
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>54.0</version>
</Package>


\e[35mdestructiveChanges.xml\e[0m
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>54.0</version>
</Package>
```

**Comment by scolladon** [comment] 2022-03-18 19:14
Aouch,

Could you give the steps to reproduce on your side please ?

And also could you try with the sfdx playground branch issue/262 and tell us the result ?

**Comment by scolladon** [comment] 2022-03-21 13:28
@1ktribble Could you give us the following:

- the result of this command : `$ git --no-pager diff --numstat --no-renames --ignore-all-space --ignore-blank-lines --ignore-cr-at-eol --word-diff-regex="|[^[:space:]]" "$compareFrom" "$compareTo" force-app`
- the content of the `.sgdignore` file

I need this information to compare expected result vs actual result

**Comment by scolladon** [comment] 2022-03-22 13:55
@1ktribble Maybe it is because of the $compareFrom and $compareTo variable not set in your environment ?
Could you run the git diff command with the right `compareFrom` and `compareTo` commit SHA and let us know the result ?

**Closed** 2022-03-24 11:16 UTC
Labels: bug, reproduction steps needed
