### ISSUE TITLE
Git delta hanging with an error with flows

### ISSUE THREAD

**Issue by nnamacha** [scolladon/sfdx-git-delta#762] opened 2024-01-19 13:09 UTC
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
---

When running git delta with changes involving FlowDefinitions the process is just hanging . When you remove the flows from the build the package.xml is created successfully

### What is the parameter and the value you used with it?

  Provide the command and the parameters you used
  sfdx sgd:source:delta --to "HEAD" --from $(git merge-base "HEAD" "origin/master")  --otead.utput . --api-version 59.0 --generate-delta

### What is the expected result?

Package.xml file generated

### What is the actual result?

  The process just hangs after generating the components before creating the package.xml files

## Steps to reproduce

---

---

$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
2022-09-05 20:28 UTC
1.22.21
v18.12.1
git version 2.39.0.windows.1
@salesforce/cli/2.23.20 win32-x64 node-v18.12.1
@copado/copado-cli 3.1.0
dependencies-cli 2.0.1
sfdx-git-delta 5.34.0
sfdx-hardis 4.5.1
sfdx-plugin-source-read 1.2.0

Uninstalled JIT Plugins:
community 3.0.10
custom-metadata 3.0.12
dev 2.1.3
devops-center 1.2.5
env 3.0.13
functions 1.22.11
signups 2.0.13
@salesforce/sfdx-plugin-lwc-test 1.1.1
@salesforce/sfdx-scanner 3.19.0

**Comment by nnamacha** [comment] 2024-01-19 13:23
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/304d8ca9-b70a-450e-86c3-4238cc850292)

**Comment by scolladon** [comment] 2024-01-19 13:38
Hi @nnamacha !

Thanks for raising this issue and thanks for contributing in making this project better!

Sorry to hear you have this kind of issue with flows.
Flow metadata has a lot of [treatment](https://github.com/scolladon/sfdx-git-delta/pulls?q=is%3Apr+translation), especially around [translation](https://github.com/scolladon/sfdx-git-delta/pull/322).

Do you have translations related to this flow definition in the repo (even not changed in the commit range you are targetting) ?

Could you send us the flow from the commit and the related translation files (anonymised if you can) so I can reproduce the issue on my side please ?

**Comment by scolladon** [comment] 2024-01-22 10:35
Hi @nnamacha 

Thanks for the flows. I checked locally and there is no performance issue when the repo contains only them.

I think the performance issue you have is related to translations.
Because when a Flow is deployed, the related translations are [dropped](https://github.com/scolladon/sfdx-git-delta/issues/321) from Salesforce, so the plugin also add the translation related to the flow in the output and in the `package.xml` to prevent that.

Could you also provide all the translations file with all their content from your repository please ?
Even if they do not contains `flowDefinitions` they will be evaluated by the plugin, then they will count.
Based on your context I'll look at a way to optimize this treatment as much as possible.

**Comment by nnamacha** [comment] 2024-01-23 08:51
In our environment we do not user translation .

**Comment by scolladon** [comment] 2024-01-23 08:57
Ok, so maybe your repository is huge ?
Can I fork it and see for myself ?

**Comment by nnamacha** [comment] 2024-01-23 09:10
Yes it is huge.

**Comment by scolladon** [comment] 2024-01-23 09:11
Ok, that's a strong lead.

It should be way much faster with this [release](https://github.com/scolladon/sfdx-git-delta/pull/760) we are currently preparing.

Stay tuned

**Comment by scolladon** [comment] 2024-01-23 15:34
Hi @nnamacha,

We released a `latest-rc` revision.
Could you install it and try with this new version please ?
Let us know the result please

**Comment by nnamacha** [comment] 2024-01-24 06:53
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/20909021-82c7-4b3b-a22c-3949331d36cb)
After upgrading to v5.35.0 we are now getting this error

**Comment by nnamacha** [comment] 2024-01-24 06:55
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/d447be64-0966-4802-8410-45993fd932d6)

**Comment by scolladon** [comment] 2024-01-24 08:15
Hi @nnamacha 

The new sgd version uses [os.availableParallelism](https://nodejs.org/api/os.html#osavailableparallelism) (only available since node `v18.14`).
The node version you have is `v18.12.1`.
I think this is the reason why you have this error, it is not available at your node version.

Sfdx cli [recommends](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm#:~:text=we%20recommend%20you%20also%20use%20the%20Active%20LTS%20version%20of%20Node.js) to us node Active LTS Version ([`v20.11.0`](https://nodejs.org/en/about/previous-releases))

I think you can test 2 things:
- either upgrade your current node maintenance LTS Version to latest => `v18.19`
- either upgrade your current node to the active LTS Version => `v20.11.0`

And let us know please !

**Comment by nnamacha** [comment] 2024-01-24 08:29
Noted

**Comment by nnamacha** [comment] 2024-01-24 11:32
Am now getting 
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/f7e707df-0e12-49f6-b74e-b2b774759690)

**Comment by nnamacha** [comment] 2024-01-24 11:32
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/1e8b5f7b-b783-4d57-b9aa-d54f7f233777)

**Comment by scolladon** [comment] 2024-01-24 13:05
Interesting @nnamacha 

Could you give me read access to the repository please (or a clone or an extract - you can send it by email, the email is on my github profile) ?
I'm afraid I need to debug in order to investigate further.

**Comment by nnamacha** [comment] 2024-01-24 13:19
@scolladon  Unfortunately I can not share . Is there a way of enabling some king of logging and I can send you the log?

**Comment by scolladon** [comment] 2024-01-24 13:30
Yes there is a way...
It is a bit more hands on and would require interaction I guess.

Would you be able to connect to a screen share so I can guide you ?
You will have to install the development version locally following those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) first with this [PR](https://github.com/scolladon/sfdx-git-delta/pull/766)
I am available today whenever you want

**Comment by scolladon** [comment] 2024-01-24 21:53
Hi @nnamacha, I think we can still do something else before having to go with a screenshare.

I have added a lot of traces in this [PR](https://github.com/scolladon/sfdx-git-delta/pull/766)
You can install it locally following those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request).
And then run sgd as usual.

To reapply the main sgd version just redo the normal installation via `sfdx plugins:install`

Please share the output as a file (it should be pretty huge so you may want to redirect sgd output to a file directly)

**Comment by nnamacha** [comment] 2024-01-25 06:04
Am not sure if am missing 
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/776bc2be-8dd0-402e-bf81-0b7663b18601)

**Comment by scolladon** [comment] 2024-01-25 08:00
What is the branch the sfdx-git-delta project is on @nnamacha ?

**Comment by scolladon** [comment] 2024-01-25 08:15
Could you run `yarn && yarn pack` inside the sfdx-git-delta folder and then retry please ?

**Comment by nnamacha** [comment] 2024-01-25 08:49
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/bbaabbd6-34fb-4d0f-abf0-e9a65c4abb74)
![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/bf61c9c5-b92d-4e97-8a1e-c2932e1ad880)

**Comment by nnamacha** [comment] 2024-01-25 09:15
[sgd_output.log](https://github.com/scolladon/sfdx-git-delta/files/14049461/sgd_output.log)

**Comment by scolladon** [comment] 2024-01-25 09:36
Weird, the issue seems to be linked to the way the repo is packed...
Maybe the repository is very old on your machine.

Could you try with a fresh clone of your repository somewhere else please, just to see if it changes the output ?
I suspect the issue comes from the repo state in your local.
If it is the case we will either [fix](https://git-scm.com/docs/git-maintenance) it or you could start from a fresh clone if all the work done is already in the remote.

**Comment by nnamacha** [comment] 2024-01-25 09:49
But why is it if I downgrade to 5.34.0 I have no issues. It works besides when there are flows in the build it takes very long but eventually completes successfully.

**Comment by scolladon** [comment] 2024-01-25 09:52
Because in this version we are using another tool to communicate with git. 
The latest-rc version uses a new adapter more portable and performant

**Comment by nnamacha** [comment] 2024-01-25 10:09
Ok let me try that

**Comment by nnamacha** [comment] 2024-01-25 10:19
I asked my colleague to try and it worked with v5.35.0

**Comment by scolladon** [comment] 2024-01-25 10:28
niiiice 🎊 

It means it is your local that needs maintenance.
You can either swap a new fresh clone
Or try to play with the `git maintenance` command locally. I think it has a lot of tools to show errors and to understand/display what it is going to do before applying it. If your repository is huge and you have a lot of development with a lot of developers then maybe you could consider having a recurrent task to maintain the remote repo once in a while.

What about the performance with flow using the `v5.35.0` ?

**Comment by scolladon** [comment] 2024-01-27 08:49
Hi @nnamacha !

How it the performance with the new version ?
Can we close this issue or is there anything else we can help with ?

**Comment by nnamacha** [comment] 2024-01-30 09:56
Apologies for the last response, I wasn't available for a couple of days. I recloned the repo and still got the same error. The other developers are also getting the same . Find attached the details from one of my colleague who was successful.
<img width="481" alt="image (1)" src="https://github.com/scolladon/sfdx-git-delta/assets/1133995/4bc9cd73-f767-4757-8cbc-4a6d09a694e9">

**Comment by nnamacha** [comment] 2024-01-30 12:12
Getting same error

![image](https://github.com/scolladon/sfdx-git-delta/assets/1133995/09c09797-0943-4c04-a1b1-5dc08b2b2960)

**Comment by nnamacha** [comment] 2024-01-30 12:20
Sorry didn't run git gc --aggressive --no-cruft --prune=now . Running it now

**Comment by scolladon** [comment] 2024-01-30 15:41
Do you have better output ?

If none, I think the issue could reside in the underlying library we are using.
I may have to patch it so it works with your use case, but doing so I need a way to reproduce the issue.
Having access to your repository would be the easiest.

**Comment by nnamacha** [comment] 2024-01-30 16:34
We are still getting it. Can we have a session where I can share my screen?

**Comment by scolladon** [comment] 2024-01-30 17:58
Yes, I'm available tomorrow afternoon (Paris time)
My email is on my public github profile

**Comment by scolladon** [comment] 2024-02-12 09:32
Hi @nnamacha !
I hope you are well, it was nice to see you guys last time.

I come back to you to know if you managed to give me some kind of access to your repository so I can reproduce locally and debug the issue.

It seems to be an isolated case but I don't want other people to get the same issue as you so I really want to investigate and put effort into fixing this issue.

Please, give me access to a repo where I can reproduce (a fork or a subset where the issue occurs anyway or an isolated scenario where the issue is reproduced)

**Comment by nnamacha** [comment] 2024-02-14 14:01
Apologies I wasn't available again for a couple of days. Am now requesting the access for you.

**Comment by nnamacha** [comment] 2024-02-15 11:42
Have you received the email granting you access?

**Comment by scolladon** [comment] 2024-02-15 12:04
Nop, not yet @nnamacha

**Comment by scolladon** [comment] 2024-02-26 13:47
@nnamacha sorry to insist, could you give me access ?

**Comment by nnamacha** [comment] 2024-02-28 10:04
Is it possible to user your salesforce email address? sailpoint.connector.ConnectorException: Exception occurred. Error message - HTTP not ended OK. Response Code - 400 Error - Your organization does not allow collaboration with the domain of the user you're inviting. Contact your admin to allow collaboration with this domain.

**Comment by nnamacha** [comment] 2024-03-15 04:09
Any update on this issue?

**Comment by scolladon** [comment] 2024-03-15 10:22
Nothing so far @nnamacha 
It is very hard to reproduce for me. I'm still working when I can on the setup to do it.

**Comment by nnamacha** [comment] 2024-04-06 14:45
Any luck?

**Comment by scolladon** [comment] 2024-04-06 14:51
not yet @nnamacha...
I really struggle to setup the environment to reproduce the issue.
I'll try to figure out how in the coming weeks

**Comment by scolladon** [comment] 2024-05-23 15:53
@nnamacha I propose to close this issue has the issue in the title has been resolved.
And I propose to follow the new issue related to git itself with this issue : #862
What do you think ?

**Comment by scolladon** [comment] 2024-06-04 12:32
Hi @nnamacha !

I close this issue because the root issue is solved.
The other issue related to isomorphic-git is tracked in the #862

**Closed by scolladon** 2024-06-04 12:32 UTC
Labels: bug
