### ISSUE TITLE
Incrementally get Profile Changes

### ISSUE THREAD

**Issue by ronika-das** [scolladon/sfdx-git-delta#198] opened 2021-10-20 07:32 UTC
### Is your proposal related to a problem?

---

Similar to how it currently for custom label and workflows, We are not able to pick changes incrementally from Profile Files

### Describe the solution you'd like

---
So for example, there is a profile file, and I am newly adding a field permission to it. I would want want only the newly Field permission to be present while running the command.

### Describe alternatives you've considered

---
Assume we have this profile file at commit abc123
![image](https://user-images.githubusercontent.com/32714099/138047433-208236dc-d32b-421a-9dd3-a85b55406b14.png)

And then we add a new field permission as follows at commit def456
![image](https://user-images.githubusercontent.com/32714099/138047550-934d12da-8161-48f9-9a65-29fabe078ec3.png)

After running the command
we want the file to look as follows

![image](https://user-images.githubusercontent.com/32714099/138047249-84a19682-0b52-4ab5-bbb9-7548e840ee3b.png)

### Additional context

---
N/A

**Comment by scolladon** [comment] 2023-03-07 13:23
Duplicate of #328

**Closed by scolladon** 2023-03-07 13:23 UTC
Labels: enhancement

**Comment by benahm** [comment] 2023-03-18 12:37
Hello, this plugin lacks this feature that is very important to deal with some metadata
that why I have created another plugin that support incremental diffs for Profiles, Translations, Workflows... 

Checkout git:delta command :  https://github.com/benahm/sfdx-mdt-plugin#sfdx-mdtgitdelta--f-string--p-string--t-string--d-string---json---loglevel-tracedebuginfowarnerrorfataltracedebuginfowarnerrorfatal


You can also read more on this article : https://benahm0.medium.com/generate-a-delta-of-your-salesforce-metadata-for-deployment-d086350074d3

**Comment by ronika-das** [comment] 2023-03-20 08:30
Thank you @scolladon  :)

There is one thing I wanted to share.

Recently for us, we had removed certain field permissions, class access etc from a Permission Set. One would expect it to not to remove anything from the Salesforce environment.
But we observed, the permissions got removed from the Permission Set on the Salesforce environment. Our intention was to only remove it from file but not the environment.

I guess this is something that should be checked once. 
We should be good for profile, custom label, translation files

**Comment by ronika-das** [comment] 2023-03-20 08:33
@benahm  thank you sharing details on your plugin and I going to check it out

**Comment by e-bacho** [comment] 2024-01-23 05:42
Hi @scolladon-sfdc, wondering whether this ever made it to a release? 

I am running `sfdx-git-delta 5.34.0 (latest-rc)` and was expecting to see *only* the changed elements inside a profile output file, but I am seeing a copy of the original (changed) file instead. Am I missing something?

**Comment by scolladon** [comment] 2024-01-23 08:41
Hi @e-bacho, sorry to ear that.

It seems to be working on my local machine (just tested).
Could you send me reproduction steps and also more information about your env please (os, git version, node version, sfdx version and sgd version)

**Comment by e-bacho** [comment] 2024-01-24 00:18
Thanks for the prompt response @scolladon. I've updated everything to latest versions:

macOS 14.2.1
git 2.39.3
node v21.6.1
@salesforce/cli/2.24.4 darwin-arm64
sfdx-git-delta 5.34.0 (5.18.0)

I added a single field permission and re-ran the delta. It turns out the field permission is picked up and added to the output file, but so are all the layout assignments and IP ranges too. Is this an expected behaviour or a bug?

![Screenshot 2024-01-24 at 11 14 53 am](https://github.com/scolladon/sfdx-git-delta/assets/5973848/f2dc78af-188d-4686-848a-9fcda6c9858d)

**Comment by scolladon** [comment] 2024-01-24 08:02
Hi @e-bacho,

Yes it is expected, layout assignments and ip ranges do not have a clear unique way to be identified (no fullname per example).
So we decided to not prune them.

I hope it helps, and happy incremental deployments

**Comment by gvivo** [comment] 2024-11-26 23:48
Hi @scolladon, I'm currently testing the latest version and testing it with my CI/CD. Props for the amazing work!

I am facing the same situation as e-bacho. We usually go generating the delta file folder, so when we get to changes in Profiles, we're getting the LayoutAssignments and LoginIpRanges when there's no need for it.
I know of a similar plugin, now deprecated, that covered this part. They focused on creating the delta files structure by default, so they covered this part of the Profiles in a different manner. I think an option to prune the LayoutAssignments and LoginIpRanges when generating the delta files would be a good addition.
In case you're curious, I'll add the link to the plugin I mentioned before: 
- https://github.com/dxatscale/sfpowerkit
- https://github.com/dxatscale/sfpowerkit/blob/main/src/impl/project/diff/profileDiff.ts

Thanks and regards,

**Comment by scolladon** [comment] 2024-11-27 08:14
Thanks @gvivo for the kind words, I'm glad the plugin helps you.

I understand it is not useful to have those metadata when they are not changed.
I agree with you, we did it this way because it was simpler and it do not harm, we can go further.

I'll work soon on an improvement to try to remove those metadata when they are not changed.
Thanks for all the refs, very helpful.

Stay tuned!
