### ISSUE TITLE
sfdx-git-delta: Command failed. Exit code: 127 Command: husky install

### ISSUE THREAD

**Issue by aveshsingh172** [scolladon/sfdx-git-delta#340] opened 2022-08-26 09:21 UTC
### Discussed in https://github.com/scolladon/sfdx-git-delta/discussions/339

<div type='discussions-op-text'>

<sup>Originally posted by **aveshsingh172** August 26, 2022</sup>
Hi Team,

Today we started getting below error. Please let me know if we have any solution for this.

sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v16.17.0
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Finished digital signature check.
Installing plugin sfdx-git-delta... yarn add v1.22.10
Installing plugin sfdx-git-delta... info No lockfile found.Installing plugin sfdx-git-delta... [1/4] Resolving packages...Installing plugin sfdx-git-delta... [2/4] Fetching packages...Installing plugin sfdx-git-delta... [3/4] Linking dependencies...Installing plugin sfdx-git-delta... [4/4] Building fresh packages...Installing plugin sfdx-git-delta... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfdx-git-delta... failed
warning sfdx-git-delta > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfdx-git-delta > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning sfdx-git-delta > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
**error /home/vsts/.local/share/sfdx/node_modules/sfdx-git-delta: Command failed.
Exit code: 127
Command: husky install
Arguments: 
Directory: /home/vsts/.local/share/sfdx/node_modules/sfdx-git-delta
Output:
/bin/sh: 1: husky: not found
    Error: yarn add sfdx-git-delta@latest --non-interactive 
    --mutex=file:/home/vsts/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/home/vsts/.cache/sfdx/yarn --check-files exited 
    with code 127**
</div>

**Comment by Dinesh-Talreja** [comment] 2022-08-26 09:42
We are facing the same issue from today morning. @scolladon : Is it related to recent changes which can been made today

**Comment by scolladon** [comment] 2022-08-26 09:43
Hi !

With which version of the plugin ?
We just shipped a fix for that (version 5.4.1)

**Comment by scolladon** [comment] 2022-08-26 09:44
Duplicate of #334

**Comment by Dinesh-Talreja** [comment] 2022-08-26 09:48
> Hi !
> 
> With which version of the plugin ? We just shipped a fix for that (version 5.4.1)

We are just using the below command

sfdx plugins:install sfdx-git-delta

**Comment by scolladon** [comment] 2022-08-26 09:54
Please share the result of those commands:
```sh
$ sfdx plugins
$ sfdx plugins:install sfdx-git-delta
$ sfdx plugins:update
$ sfdx plugins
```

**Comment by Dinesh-Talreja** [comment] 2022-08-26 10:11
@scolladon : It seems the issue is resolved now. Thanks for the quick fix.

**Closed** 2022-08-26 10:19 UTC

**Comment by vaibhavdangar-woolies** [comment] 2022-08-29 05:18
Hi @scolladon , many thanks to fix the issue. Please advise if there is a way we can specify a 'stable' tag instead of 'latest' version. So Prod pipelines can use 'stable' plugin version while we experiment with latest version in devp. sandbox.

**Comment by scolladon** [comment] 2022-08-29 07:47
Hi @vaibhavdangar-woolies this is a very nice suggestion.
I'll look into it.
I understand we need to protect production environment from the potential issues we create while adding features.

**Comment by scolladon** [comment] 2022-08-30 08:56
Issue seems to be linked to [this one in the sfdx-cli](https://github.com/forcedotcom/cli/issues/1664).
It could explain why we faced it at that time

**Comment by Ishita2007** [comment] 2023-02-01 12:32
> @scolladon : It seems the issue is resolved now. Thanks for the quick fix.
@scolladon :can you please tell what fix you have done ?

**Comment by scolladon** [comment] 2023-02-01 13:22
@Ishita2007 we [removed the `postinstall` script](https://github.com/scolladon/sfdx-git-delta/pull/336/files) added by the husky upgrade we did.

Here is a [broader communication](https://github.com/scolladon/sfdx-git-delta/discussions/346) about this issue
