### ISSUE TITLE
[custom labels] double closing tag should not make sgd failed

### ISSUE THREAD

**Issue by alexmodis** [scolladon/sfdx-git-delta#155] opened 2021-06-22 15:54 UTC
The synthax below is making sgd failed to generate a proper custom label file output but Salesforce deployment is working well.
```
    <labels>
        <fullName>XXXX</fullName>
        <language>en_US</language>
        <protected>false</protected>
        <shortDescription>XXXX</shortDescription>
        <value>Delivery Delay</value>
    </labels>
    </labels>
```

Should we do something?

**Comment by scolladon** [comment] 2021-06-23 08:30
Hi @alexmodis !

Thanks for raising this !
How can I reproduce the fail from the plugin ?

**Comment by mehdisfdc** [comment] 2021-06-30 15:44
@alexmodis Can you confirm that this double closing tag is cased by a local change on the file (manual edit, or issue caused by a merge conflict resolution)? 
In that case, I would think that it's OK for SGD not to support this invalid file format. Even if you could deploy it, you are supposed to have it in your repo in the first place.

**Comment by alexmodis** [comment] 2021-06-30 18:51
@mehdisfdc at least an sgd error would be great :D but its just a nice to have

**Comment by mehdisfdc** [comment] 2021-07-01 06:44
Yes I agree @alexmodis

**Closed** 2021-07-06 13:36 UTC
Labels: enhancement

**Comment by scolladon** [comment] 2021-07-06 13:49
Hi @alexmodis !

New version 4.7 released today enforces xml validation and throw a warning when encountering wrongly structured xml files

**Comment by alexmodis** [comment] 2021-07-06 14:40
🍾  thx :)
