### ISSUE TITLE
Workflow diff detection KO

### ISSUE THREAD

**Issue by alexmodis** [scolladon/sfdx-git-delta#192] opened 2021-09-27 08:46 UTC
Hi @scolladon  :)

Repro branch : issue/192/workflow-rule

Command : sfdx sgd:source:delta -d -t HEAD -f HEAD~1 -r . -i .forceignore -o output

Repro steps : 
Add new fieldUpdates in a WFR and see that output doesnt contains this new diff.

Expected result : 
BE_statut echeance (and other diff) is in output file :
![image](https://user-images.githubusercontent.com/60091729/134876691-5752e3a3-e275-475b-b861-3ebf663adb1e.png)

Current result : 

BE_statut_echeance (and other diff) are not there

Versions:
Node version : 
+ node --version
v16.10.0
+ echo 'Npm version : '
+ npm --version
Npm version : 
7.24.0
sfdx-git-delta 4.9.0

**Comment by scolladon** [comment] 2021-09-27 09:13
Hi @alexmodis !

Thanks for this report !

I gave you access to the [reproduction-playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) so you can create the branch in there. Let us know when done so we can investigate.

Could you share the content of the `.forceignore` file please ?
I see the version of node is `v16.10.0`, the plugin is designed to run on `v14`, not sure yet if this is impacting but I'll try that.

Seb

**Comment by alexmodis** [comment] 2021-09-27 09:15
@scolladon the forceignore file is in the branch too.

The branch is available in your repro playground.

**Comment by scolladon** [comment] 2021-09-27 09:56
Here is the result I have on my machine: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Echeance__c</members>
        <name>Workflow</name>
    </types>
    <types>
        <members>Echeance__c.BE_statut_echeance</members>
        <members>Echeance__c.statut_echeance</members>
        <members>Echeance__c.unicite_echeance</members>
        <name>WorkflowFieldUpdate</name>
    </types>
    <types>
        <members>Echeance__c.BE_informer_LOG_update_echeance</members>
        <members>Echeance__c.Formatage date echeance</members>
        <members>Echeance__c.informer_LOG_update_echeance</members>
        <members>Echeance__c.unicité Echeance</members>
        <name>WorkflowRule</name>
    </types>
    <version>52.0</version>
</Package>
```

using the command `sfdx sgd:source:delta -d -t HEAD -f HEAD~1 -r . -i .forceignore -o output`
Does it looks like what you expect @alexmodis ?

Here is my env : 
Darwin Kernel Version 19.6.0: Tue Aug 24 20:28:00 PDT 2021; root:xnu-6153.141.40~1/RELEASE_X86_64
yarn 1.22.11
node v14.16.0
git version 2.33.0
sfdx-cli/7.118.1 darwin-x64 node-v14.16.0
sfdx-git-delta 4.9.0

**Comment by alexmodis** [comment] 2021-09-27 11:29
yes package.xml is ok. But the workflow file itself is wrong as it does not contains Echeance__c.BE_statut_echeance for example.

**Comment by scolladon** [comment] 2021-09-27 11:33
Here is the workflow file I have : 
```xml
<?xml version="1.0" encoding="utf-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldUpdates>
        <fullName>BE_statut_echeance</fullName>
        <field>Statut__c</field>
        <literalValue>En attente</literalValue>
        <name>statut echeance</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>statut_echeance</fullName>
        <field>Statut__c</field>
        <literalValue>En attente</literalValue>
        <name>statut echeance</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>unicite_echeance</fullName>
        <description>unicite echeance</description>
        <field>unicit_echeance__c</field>
        <formula>Poste_d_offre__r.Id &amp;  &apos;_&apos; &amp; RecordType.Name &amp; &apos;_&apos; &amp;   TEXT(Date_echeance__c)</formula>
        <name>unicite echeance</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>BE_informer_LOG_update_echeance</fullName>
        <actions>
            <name>BE_Email_notif_modif_echeance</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>BE_statut_echeance</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <booleanFilter>((1 AND 2 AND 3 AND 7) OR (4 AND 5 AND 6)) AND 8</booleanFilter>
        <criteriaItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>Commerce_lightning user,Direction Commerciale_lightning user</value>
        </criteriaItems>
        <criteriaItems>
            <field>Echeance__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commerce</value>
        </criteriaItems>
        <criteriaItems>
            <field>Echeance__c.Statut__c</field>
            <operation>equals</operation>
            <value>Traité</value>
        </criteriaItems>
        <criteriaItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>Service_Client_ADV_Lightning_User</value>
        </criteriaItems>
        <criteriaItems>
            <field>Echeance__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>ADV</value>
        </criteriaItems>
        <criteriaItems>
            <field>Echeance__c.Statut__c</field>
            <operation>equals</operation>
            <value>Traité</value>
        </criteriaItems>
        <criteriaItems>
            <field>Poste_offre__c.co_wfl_t__c</field>
            <operation>notEqual</operation>
            <value>20,40</value>
        </criteriaItems>
        <criteriaItems>
            <field>User.CountryCode</field>
            <operation>equals</operation>
            <value>BE</value>
        </criteriaItems>
        <description>informer les responsables  de la désactivation d&apos;un écheancier via un email</description>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>Formatage date echeance</fullName>
        <actions>
            <name>Formatage_date_echeance</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>User.Bypass_Workflows__c</field>
            <operation>equals</operation>
            <value>False</value>
        </criteriaItems>
        <criteriaItems>
            <field>Poste_offre__c.Name</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>Formatage de la date échéance en mois année pour l&apos;extraction mensuelle vers APO</description>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>informer_LOG_update_echeance</fullName>
        <actions>
            <name>Email_notif_modif_echeance</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>statut_echeance</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>Commerce,Direction Commerciale</value>
        </criteriaItems>
        <criteriaItems>
            <field>Echeance__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commerce</value>
        </criteriaItems>
        <criteriaItems>
            <field>Echeance__c.Statut__c</field>
            <operation>equals</operation>
            <value>Traité</value>
        </criteriaItems>
        <criteriaItems>
            <field>Poste_offre__c.co_wfl_t__c</field>
            <operation>notEqual</operation>
            <value>20,40</value>
        </criteriaItems>
        <criteriaItems>
            <field>User.CountryCode</field>
            <operation>equals</operation>
            <value>FR</value>
        </criteriaItems>
        <description>informer les responsables  de la désactivation d&apos;un écheancier via un email</description>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>unicité Echeance</fullName>
        <actions>
            <name>unicite_echeance</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>User.Bypass_Workflows__c</field>
            <operation>equals</operation>
            <value>False</value>
        </criteriaItems>
        <criteriaItems>
            <field>Poste_offre__c.Name</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <description>unicité de l&apos;échéance</description>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
```

**Comment by alexmodis** [comment] 2021-09-27 11:40
Ok so we don't have same output with node version 16.x
Let me force the pipeline to use exact version and come back with results :)

**Comment by alexmodis** [comment] 2021-09-27 12:24
Seems that node version is not guilty :'(
So something with the git diff I guess.

Can you remember me the git diff command that you are using please so that I can check if the git diff contains those diff?

PS: package.xml doesnt contains the workflow field update line in the pipeline (but it does in repro playground) in contrary to what I stated above.

**Comment by scolladon** [comment] 2021-09-27 12:52
For the global diff we use this command: 
```sh
$ git --no-pager diff --name-status --no-renames HEAD~1 HEAD
````

For in file diff we use this command: 
```sh
$ git --no-pager diff --no-prefix -U200 HEAD~1 HEAD
```

Maybe this is an issue with the windows (if windows involved somehow, or powershell or something different than unix bash).

Or maybe it is a regression, do you remember a older working version you could try with ?

**Comment by alexmodis** [comment] 2021-09-27 14:28
```
diff --git force-app/way/default/workflows/Echeance__c.workflow-meta.xml force-app/way/default/workflows/Echeance__c.workflow-meta.xml
index 0a33363d1..15057d348 100644
--- force-app/way/default/workflows/Echeance__c.workflow-meta.xml
+++ force-app/way/default/workflows/Echeance__c.workflow-meta.xml
@@ -1,221 +1,249 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
     <alerts>
         <fullName>Alerte_refus_d_une_ch_ance</fullName>
         <description>Alerte refus d’une échéance</description>
         <protected>false</protected>
         <recipients>
             <type>creator</type>
         </recipients>
         <senderType>CurrentUser</senderType>
         <template>PA_et_offres/Alerte_refus_d_une_ch_ance</template>
     </alerts>
     <alerts>
         <fullName>BE_Email_notif_modif_echeance</fullName>
         <description>Email_notif_modif_echeance</description>
         <protected>false</protected>
         <recipients>
             <recipient>BE_Log_Planner</recipient>
             <type>role</type>
         </recipients>
         <senderType>CurrentUser</senderType>
         <template>PA_et_offres/Email_notif_modif_echeance</template>
     </alerts>
     <alerts>
         <fullName>Email_notif_modif_echeance</fullName>
         <description>Email_notif_modif_echeance</description>
         <protected>false</protected>
         <recipients>
             <recipient>Coordinateur_Logistique</recipient>
             <type>role</type>
         </recipients>
         <senderType>CurrentUser</senderType>
         <template>PA_et_offres/Email_notif_modif_echeance</template>
     </alerts>
+    <fieldUpdates>
+        <fullName>BE_statut_echeance</fullName>
+        <field>Statut__c</field>
+        <literalValue>En attente</literalValue>
+        <name>statut echeance</name>
+        <notifyAssignee>false</notifyAssignee>
+        <operation>Literal</operation>
+        <protected>false</protected>
+        <reevaluateOnChange>true</reevaluateOnChange>
+    </fieldUpdates>
```

**Comment by scolladon** [comment] 2021-11-17 13:50
One month without moving forward on this one.
If you have any element to help reproducing and isolating the issue please raise your hand !

Else we will close this issue

**Comment by jonathanwiesel** [comment] 2021-11-17 15:38
Sorry for the late reply, I'll try send some repro steps during this week

**Comment by jonathanwiesel** [comment] 2021-11-17 18:25
In our use case de diff represented only changing the recipient of an email alert.
Similarly, changing the sharedTo in a sharing rule also reproduced the issue

**Comment by scolladon** [comment] 2021-11-22 19:34
Hi @jonathanwiesel !

I just tried locally and I do not reproduce the issue...

What I did :

1. Created a workflow file with a `rule` and an `emailAlert` => commit it
2. Changed the recipient of the `emailAlert` => commit it
3. run sgd (`sfdx sgd:source:delta -f "660e6cf374274a746ee1a36246d3c423e79122ac" -t "d9e8361d42cbc8edd83440151118f5156ade4f93" -d`) on the last commit and had look at the result: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Event</members>
        <name>Workflow</name>
    </types>
    <types>
        <members>Event.TestEmailAlert</members>
        <name>WorkflowAlert</name>
    </types>
    <version>52.0</version>
</Package>
```

I put everything in the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/192) so anyone can try it locally

### My env:
**System**: Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64
**yarn**: 1.22.17
**node**: v14.18.1
**git**: version 2.33.1
**sfdx-cli**: 7.126.0 darwin-x64 node-v14.18.1
**sfdx-git-delta**: 4.10.0

**Comment by jonathanwiesel** [comment] 2021-11-22 22:29
@scolladon sorry, I'm unable to replicate it anymore, maybe it was due to an old version of sfdx or the plugin (or just an error on our CI/CD).

My most sincere apologies

**Comment by arafesthain** [comment] 2021-12-28 12:48
Hi @scolladon,
Hope you enjoyed your christmas period :)
I still get the issue on Ubuntu 20.04.3 LTS. This time I'm on a totally different git project/client and workflow file has a lot of modifications. No workflow in package.xml nor in output folder.

Will try to put this in your repro playground soon.

node --version
v14.6.0
Npm version 
6.14.6
sfdx-cli/7.132.0 linux-x64 node-v14.6.0
sfdx-git-delta 4.12.0

**Comment by arafesthain** [comment] 2021-12-30 15:27
@scolladon seems that the problem is not with workflow rule itself. We see it thanks to missing worklow rule directory that is missing but truth is there is an error before the "W" letter directory in a previous letter directory metadata. This error is not poping up and so we are just getting a silent error.

Sucess is true but in fact it is not..

I found this because we have an other directory after "main" called "sharepoint" and there is no "sharepoint" directory in output even if there is diff in it.
If I "git mv sharepoint to a-sharepoint", the directory is well outputed. If I "git mv sharepoint z-sharepoint" directory is not in output. 

Hope it was a little bit readable 😂

**Comment by scolladon** [comment] 2021-12-30 16:06
Interesting ! Thanks for the investigation
Sounds like a real bug to me... I do not understand deeply how to reproduce it locally, have you been able to setup a branch in the reproduction playground so I can test on my side ?

**Comment by arafesthain** [comment] 2021-12-30 16:15
I"m not sure I can find a way to repro in the playground. But maybe I cand sen you a read only PAT on our github repo.
Let me check.

**Comment by scolladon** [comment] 2021-12-30 23:22
Sure, here are my [github public ssh keys](https://github.com/scolladon.keys)

**Comment by arafesthain** [comment] 2022-01-03 08:22
Hi, 

Sorry but this key can't be used : [Key already used](https://docs.github.com/en/authentication/troubleshooting-ssh/error-key-already-in-use
)

**Comment by scolladon** [comment] 2022-01-03 10:26
Could you fork it into a private repo and give me access to that private fork of your own ?

**Comment by arafesthain** [comment] 2022-01-03 10:28
Nope fork is disabled on all our repos. Any other idea ?

**Comment by scolladon** [comment] 2022-01-03 12:06
Yep !

We can try doing it manually

Create a <private-repo> (blank, without anything) on github, give access to my github user

```sh
$ git clone <repo-to-fork> <repo-folder>
$ cd <repo-folder>
$ git remote remove origin
$ git remote add origin <private-repo>-url
$ git push origin <principal-branch>
```

**Comment by arafesthain** [comment] 2022-01-03 12:47
Done.

Go on develop branch (https://github.com/arafesthain/repro-issue-192-silent-dead)
Then sfdx sgd:source:delta -d -t HEAD -f origin/main -r . -o output

See that sharepoint folder is not in output & that there is no more metadata detected after remoteSiteSettings meta in force-app/main

**Comment by scolladon** [comment] 2022-01-03 15:37
Thanks !
I have been able to troubleshoot :) 
The issue comes from the buffer size used internally to spawn commands.

I will try to design a buffer free solution to avoid issue with little buffer context (CI per exemple)

**Closed** 2022-01-05 14:50 UTC
Labels: bug

**Comment by arafesthain** [comment] 2022-01-05 15:08
Amazing let's try this :)
