### ISSUE TITLE
Not working for Fork Public PR

### ISSUE THREAD

**Issue by Sarveshgithub** [scolladon/sfdx-git-delta#344] opened 2022-08-29 17:50 UTC
I have created GitHub action for My Repo and I am using `sfdx-git-delta`. But Action failing on fork public PR. Please advise how to solve this issue. thanks!
[Link of Action](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/optimize/.github/workflows/PR_Validate.yml)
[Link of PR ](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/pull/58)
[Link of Error Message](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/runs/8076370570?check_suite_focus=true#step:13:24)

**Comment by scolladon** [comment] 2022-08-29 18:38
Hi @Sarveshgithub !

I think the issue you are facing is the deployment wants to deploy from `changed-sources` folder where it is not defined as a source folder in the [`sfdx-project.json`](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/optimize/sfdx-project.json).

Source manageable by sfdx-cli [must be located](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm#:~:text=packageDirectories%20(required)) inside folder declared in the `sfdx-project.json`

**Comment by Sarveshgithub** [comment] 2022-08-30 04:23
@scolladon , This is working fine when I raise PR against the branch, this is failing for another user ( new forking User) when an outside user tries to create PR. where  I need to add exactly in [sfdx-project.json](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/optimize/sfdx-project.json) `changed-sources` folders.

**Comment by scolladon** [comment] 2022-08-30 08:24
I think you could try adding a packageDirectory [here](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/be5935b9b43fa8297bc05f31c34d00cb86b2ded0/sfdx-project.json#L2), like this:
```json
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    },
    {
      "path": "changed-sources",
      "default": false
    },
  ],
...
```

**Comment by Sarveshgithub** [comment] 2022-08-30 08:38
@scolladon thanks for the response, I have added the above code, still showing the error 😩. 
[latest action error](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/runs/8087798880?check_suite_focus=true)

**Comment by scolladon** [comment] 2022-08-30 08:48
One thing I want to try, can you remove the quote surrounding the path? 
`sfdx force:source:deploy -p changed-sources/force-app --checkonly --testlevel RunLocalTests  --json`

And also, do you reproduce the issue locally?

**Comment by Sarveshgithub** [comment] 2022-08-30 09:27
@scolladon I removed quotes, but still not working, the issue with only in `fork`
- If I raise PR the action is working with no error [PR](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/pull/57)
- Fork PR action is failing [Action](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/runs/8088578834?check_suite_focus=true)
- Run the above command locally it's failing
<img width="1425" alt="Screenshot 2022-08-30 at 2 52 54 PM" src="https://user-images.githubusercontent.com/40709233/187401387-34b43f7d-8fa0-4154-ae7b-4ab8e4566035.png">

**Comment by scolladon** [comment] 2022-08-30 09:52
Please share the result of this command, it will provide us information with the context of execution:
```sh
$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
```

Does it fails with any other folder ?
Per exemple if you create a new folder `poc` try to deploy (`sfdx force:source:deploy -p poc --checkonly`) that what is the result?

**Comment by Sarveshgithub** [comment] 2022-08-30 10:28
Here is the results 

> zsh: command not found: $
zsh: command not found: yarn
v16.16.0
git version 2.37.1
sfdx-cli/7.162.0 darwin-x64 node-v16.13.1
@salesforce/lwc-dev-server 2.11.0

I am using git-delta only in workflow Actions, Now sure local config can help here. thanks!

**Comment by scolladon** [comment] 2022-08-30 10:52
I am trying to reproduce this issue.
I read there is an issue when you [test locally](https://github.com/scolladon/sfdx-git-delta/issues/344#:~:text=Run%20the%20above%20command%20locally%20it%27s%20failing), hence I ask for your local setup.

do you have deployment issue with [other folder](https://github.com/scolladon/sfdx-git-delta/issues/344#:~:text=Per%20exemple%20if%20you%20create%20a%20new%20folder%20poc%20try%20to%20deploy%20(sfdx%20force%3Asource%3Adeploy%20%2Dp%20poc%20%2D%2Dcheckonly)%20that%20what%20is%20the%20result%3F) as well ?

**Comment by Sarveshgithub** [comment] 2022-08-30 11:00
I removed folder Now it's working `sfdx force:source:deploy -p force-app --checkonly --testlevel RunLocalTests  --json`
[Workflow Action](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/runs/8090340684?check_suite_focus=true). But this validates the whole code. instead of Delta changes.

**Comment by scolladon** [comment] 2022-08-30 11:10
I want to test if the deploy issue is related to the sources generated by sgd or if it is related to any other sources than force-app in your case.

Please, create a dummy folder to test that.
Example here (you need to adjust it to your context):
```sh
$ cd <your repo folder>
$ mkdir sample
# put some metadata in sample (like one or two classes, respect the folder hierarchy, classes should be under classes folder)
$ sfdx force:source:deploy -p sample --checkonly --testlevel RunLocalTests --json
```

What is the result of that ?

**Comment by Sarveshgithub** [comment] 2022-08-30 11:17
Yes I tested above, it worked.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40709233/187423172-9c9308c0-0aa6-49ac-b271-1443be91f68a.png">

**Comment by scolladon** [comment] 2022-08-30 11:20
Ok so we could try a folder name without hyphen for the changed-sources.

Both way to try this:
- Renaming sample to sam-ple and retry sample
- renaming changed-sources to delta and redo the sgd scenario with this new folder

**Comment by Sarveshgithub** [comment] 2022-08-30 11:27
folder with hyphen is also working.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40709233/187425176-c432e62c-9b9d-4543-a820-e0de91b9d629.png">

**Comment by scolladon** [comment] 2022-08-30 11:31
Ok, thanks for all the information.

What is the content of changed-sources when it failed in the CI ?

**Comment by Sarveshgithub** [comment] 2022-08-30 11:43
So I have a public [repo](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable), I am adding a CI process for the new fork or New User's PR. 
- I want every PR should first validate no matter if I raise PR or New User raise PR - this works fine
- Next, i want only Delta changes should validate, so I used `sgd` in [Action](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/be36a21462ea93174255751f3ac2a56a86175b1d/.github/workflows/PR_Validate.yml#L70) - this works fine if i raise PR. this is failing for other Github User raise PR. 

At the moment I am testing for Other Github User, only modifying Apex class so `sgd` can check and validate only that particular class , so [here](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/pull/58/files) is the commit on class. this should validate. But unfortunately, this does not work for outside Github Users.

**Comment by scolladon** [comment] 2022-08-30 15:54
That is special.

So, the plugin behave particularly when executed within a github action when this github action is triggered by a fork (a user outside the repository).
Is there any specificity of the github user when running via a fork ?

I seems to be related to github action specificity with fork PR, maybe it is linked to how sfdx plugins work as well.
I'll try to find more time end of week to troubleshoot with a dummy repository if you do not find a solution.
Maybe you should raise this issue to sfdx-cli / github action as well, they will help us (if you do so, add a comment with those issues link here)
I don't understand what in our plugin code can lead to this behaviour but we never know.

**Comment by scolladon** [comment] 2022-08-31 14:01
@Sarveshgithub I think I have an idea why there is an issue.
It is worth a try.

I noticed the github workflow is executed [on pull_request_target](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/optimize/.github/workflows/PR_Validate.yml#L6).
It means the context loaded is the target branch.
My guess is that this is leading to confusion on what is expected.
Could you try by changing `pull_request_target` to `pull_request` please ?

**Comment by Sarveshgithub** [comment] 2022-08-31 14:06
@scolladon `pull_request` does not allow Github Secret to share with fork User. So with `pull_request_target` Action can get the secret access.

**Comment by scolladon** [comment] 2022-08-31 14:21
@Sarveshgithub yes, I get that.
`pull_request_target` also put the context to the target branch.
Meaning if your target branch is `main` it will clone the repository at `main` state.
When doing a delta deploy with `HEAD` and `HEAD~1` it will compare last main commit with previous last main commit.
Which can lead to no metadata in the `changed-sources` depending on what is in those commit.
[Documentation says](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target:~:text=Avoid%20using%20this%20event%20if%20you%20need%20to%20build%20or%20run%20code%20from%20the%20pull%20request.) it should be avoided if build is needed (which is the case here)

My point here is, if you want to look at the commits from the PR to build them or delta generate them, you cannot use `pull_request_target` this way because it does not retrieve the commit from the PR branch, you need to use `pull_request` instead

**Comment by scolladon** [comment] 2022-09-01 09:23
@Sarveshgithub if you need to keep pull_request_target in order to keep access to your secret to be able to deploy in your CI, then you should checkout manually the merge commit from the PR.
It is explained [here](https://github.com/orgs/community/discussions/25721)

You could do the following (example, not tested):
```yaml
- name: Checkout
      uses: actions/checkout@v3
      with:
		fetch-depth: 0
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
```

Let me know if that help !

**Comment by scolladon** [comment] 2022-09-01 11:12
@Sarveshgithub the "HEAD~1" commit is not detected because it is not checked out.
Maybe because the workflow miss `force-depth: 0` parameter

I also think the workflow should compare with the target branch instead of HEAD^1 in this situation. Because HEAD^1 is not the base branch, it is the commit just after the last from the branch currently checkout, which is from the pr branch.

So maybe you should try and poc around using github.base_ref (I have not tested, it could be a strong lead, you may have to specifiy the origin here like this: "origin/${{ github.base_ref }}", coming from a fork the origin is not the same):
```yaml
- name: "Create delta packages for new, modified or deleted metadata"
              run: |
                  mkdir changed-sources
                  sfdx sgd:source:delta --to "HEAD" --from "${{ github.base_ref }}" --output changed-sources/ --generate-delta --source force-app/
```

**Comment by Sarveshgithub** [comment] 2022-09-01 12:18
@scolladon Tried again didn't work 😩 [action](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/runs/8134834957?check_suite_focus=true)

**Comment by scolladon** [comment] 2022-09-01 12:41
The checkout option only takes the [last commit](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/optimize/.github/workflows/PR_Validate.yml#L29).
It should ask for the all history with [`fetch-depth: 0`](https://github.com/scolladon/sfdx-git-delta/issues/344#:~:text=v3%0A%20%20%20%20%20%20with%3A-,fetch%2Ddepth%3A%200,-ref%3A%20%24%7B%7Bgithub)

**Comment by Sarveshgithub** [comment] 2022-09-02 09:12
@scolladon I have added `fetch-depth : 0`, but still didn't work. [action](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/runs/8135460702?check_suite_focus=true)

**Comment by scolladon** [comment] 2022-09-02 12:20
Have you try removing the "origin/" as well ?

```yaml
- name: "Create delta packages for new, modified or deleted metadata"
  run: |
      mkdir changed-sources
      sfdx sgd:source:delta --to "HEAD" --from "${{ github.base_ref }}" --output changed-sources/ --generate-delta --source force-app/
```

**Comment by Sarveshgithub** [comment] 2022-11-28 11:13
@scolladon please close this issue. as now I am doing a full deployment

**Comment by scolladon** [comment] 2022-11-28 11:20
Thanks for your quick answer!
I close the issue.

Why you did not go for incremental deployment in the end ?

**Closed by scolladon** 2022-11-28 11:20 UTC
Labels: help wanted, question

**Comment by Sarveshgithub** [comment] 2022-11-29 04:04
@scolladon yhea i tried so much, but unfortunately, sdg not working on public repo PRs.
