### ISSUE TITLE
translationJSON?.Translations?.flowDefinitions?.forEach is not a function

### ISSUE THREAD

**Issue by briank73** [scolladon/sfdx-git-delta#341] opened 2022-08-26 19:15 UTC
In version 5.4.1. we get the error below - in version 5.3.1 it works fine. And sorry for not being able to provide more info :-(

{
  "error": "translationJSON?.Translations?.flowDefinitions?.forEach is not a function",
  "output": "changes",
  "success": false,
  "warnings": []
}

**Comment by scolladon** [comment] 2022-08-26 22:22
Duplicate of #342

**Closed by scolladon** 2022-08-26 22:22 UTC
