### ISSUE TITLE
[Metadata Files Scraping] Auto generation & scraping of profile, permission set & translation files 

### ISSUE THREAD

**Issue by laithal** [scolladon/sfdx-git-delta#328] opened 2022-08-17 12:25 UTC
### Is your proposal related to a problem?

---

We often hit the limit of 10K lines with the profile & permission set metadata file. It is extremely hard to finetune those files as they require lots of manual work and advanced development skills.

### Describe a solution you propose

---

Scrub the profile, permission set & translation metadata files based on recent changes, and or the package.xml file. Would be great to have --parameter for each scenario.

### Describe alternatives you've considered

---

No current good-known alternative solutions.

### Additional context 

---

**Comment by scolladon** [comment] 2022-08-17 12:43
Hi @laithal !

Thanks for this great suggestion!

I think we could imagine a parameter to enable scoping profile, permissionset, translation and objectTranslation files based on what has been added/changed in it and the content of the package.xml.
The goal here is to make sure those files contain only what is relevant for the context of the deployment.

I'll try to work on it and use this [PR](https://github.com/scolladon/sfdx-git-delta/pull/90) to add this feature

**Comment by laithal** [comment] 2022-08-17 13:06
Absolutely. That's exactly it. 
Thank you so much. This would ease deployments by a significant amount.

**Comment by scolladon** [comment] 2023-04-06 14:06
Hi @bishwambharsen !

Thanks for those kind words and thanks for your interest on the release of this!
We are planning to deliver it in this month (april) most probably.
We still have some work to do to make sure it works without regression (E2E test to build).

Stay tuned, it will be released very soon.

**Comment by scolladon** [comment] 2023-04-07 07:14
Would you like to be beta tester @bishwambharsen?

It is possible to do so and it would be really helpful to have your early feedback on this.

Here is [how you can do it on your machine](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request).
Let us know anything you find.
The list of scrapped metadata is in the PR description if you need an exhaustive list of supported metadata with this behavior.

I think we managed to deal with all of the metadata that behave this way.
If you think we miss one of them let us know, we will add it.

_PermissionSet is not in the list because it was not scrappable in my tests, when removing part of a Permission Set file and deploy the configuration removed is also removed in the org. delta content of this metadata is not possible (unlike profile)_

**Closed** 2023-04-21 06:42 UTC
Labels: enhancement

**Comment by scolladon** [comment] 2023-04-21 07:35
Hi @bishwambharsen !

We have extended the content pruning algorithm to more types (I think [all of them](https://github.com/scolladon/sfdx-git-delta/pull/533) now).

It is available in the `latest-rc` channel, ready for you to use it.
If you find any issue feel free to create a github issue so we can fix it quickly hopefully.

**Comment by bishwambharsen** [comment] 2023-04-27 03:30
The -W option seems to be broken. 😢 although we can format both versions using prettier to handle that but earlier -W option used to ignore the white space and line breaks. Not a deal breaker but just thought you should know. And thanks again for the new feature. 🙏😊

**Comment by scolladon** [comment] 2023-04-27 06:30
Hi @bishwambharsen, thank you very much for the feedback.

About the `-W` issue, thank you for noticing it and for raising it.
How can I reproduce ? I'll try to fix it asap

**Comment by bishwambharsen** [comment] 2023-04-27 06:37
We usually generate the delta by comparing the develop branch (git flow strategy) with main. If one of the versions isn't formatted then despite having same content, it treats the formatting difference as a delta and includes the file in the delta package. We were able to bypass it earlier using -W option.

**Comment by scolladon** [comment] 2023-04-27 06:47
Could you give me the kind of difference that are not ignored ? (if you could give me the diff it would be very helpful).

Also does it work with actual `latest` version (not `latest-rc`) ?

**Comment by bishwambharsen** [comment] 2023-04-27 07:29
Mostly formatting related differences like white spaces and new lines that are usually introduced by Prettier. It works with latest but didn't work with latest-rc. I'll monitor it for now and will see if it happens to other files too. As of now it happens to only Apex classes (.cls and .cls-meta.xml). I'll keep you posted. If I can consistently reproduce it a few more times then I'll add more information regarding the issue. If it is not reproduced again then also I'll notify you.

**Comment by scolladon** [comment] 2023-04-27 09:14
I'm not able to reproduce locally using `latest-rc` @bishwambharsen.

I'm using this [branch](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/262) in the reproduction playground (related to a similar previous issue).
The last commit of this branch introduced white characters (eol, tab, space) in the `Test2` apex class.
Then I executed this command (with `latest-rc` version => `5.18.0`):
```sh
sfdx sgd:source:delta -f "HEAD~1" -d -W 
```

The output does not copy the apex class neither add an entry in the package.xml.

Could you help me reproduce please ?
What kind of change to what kind of metadata should I add to be able to reproduce the issue ?

**Comment by scolladon** [comment] 2023-04-28 07:59
@bishwambharsen feel free to create an issue when you'll be able to reproduce it
Please add details step to help me reproduce it!
