### ISSUE TITLE
I am getting Warning like in both  sfdx-cli and  Salesforce/CLI 

### ISSUE THREAD

**Issue by vivelan** [scolladon/sfdx-git-delta#761] opened 2024-01-17 06:56 UTC
Hi,

I am getting Warning like in both  sfdx-cli and  Salesforce/CLI - like '(node:33036) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.'

Thanks

**Comment by scolladon** [comment] 2024-01-17 09:06
Hi @vivelan

This issue is already tracked.

Duplicate of #619 

**TL;DR**: You can ignore this warning, it will be fixed when we migrate on the new sf v2 plugin architecture

**Closed** 2024-01-17 09:06 UTC
Labels: bug
